### ISSUE TITLE
using `io.spring.dependency-management` to lock transitive dependencies to incompatible versions

### ISSUE THREAD

**Issue by AjinxPatil** [diffplug/spotless#1075]
### Problem

`spotlessJava` task fails when using `googleJavaFormat()` with:
```
java.lang.NoSuchMethodError: 'java.lang.Comparable com.google.common.collect.Comparators.max(java.lang.Comparable, java.lang.Comparable)'
```

### Version
Spotless: 6.1.2
Gradle: 7.3.1
Java: 11

### build.gradle
```
plugins {
    id 'com.diffplug.spotless' version '6.1.2'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

repositories {
    maven {
        url 'https://<private>/artifactory/maven-abc-release'
    }
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'com.abc:abc-parent:8.125.0'
        mavenBom 'software.amazon.awssdk:bom:2.17.106'
    }
}

dependencies {
    implementation 'com.abc:abc-starter-springmvc'
    implementation 'com.abc:connector-core'
    implementation 'software.amazon.awssdk:s3'
    testImplementation 'org.assertj:assertj-core'
    testImplementation 'junit:junit'
    testImplementation 'org.mockito:mockito-core'
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'org.springframework:spring-test'
    testImplementation 'org.springframework.boot:spring-boot-test'
}

spotless {
    java {
        googleJavaFormat()
    }
}

```

### Error
```
> Task :core:spotlessJava FAILED
Step 'google-java-format' found problem in 'src/main/java/com/abc/dwingest/resource/MyFirstResilientHttpClientExample.java':
null
java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.GeneratedMethodAccessor707.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.diffplug.spotless.java.GoogleJavaFormatStep$State.lambda$createFormat$1(GoogleJavaFormatStep.java:176)
        at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:32)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:190)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:92)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:78)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
        at org.gradle.api.internal.project.taskfactory.IncrementalInputsTaskAction.doExecute(IncrementalInputsTaskAction.java:32)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        ...
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NoSuchMethodError: 'java.lang.Comparable com.google.common.collect.Comparators.max(java.lang.Comparable, java.lang.Comparable)'
        at com.google.googlejavaformat.java.javadoc.JavadocWriter.requestWhitespace(JavadocWriter.java:272)
        at com.google.googlejavaformat.java.javadoc.JavadocWriter.requestWhitespace(JavadocWriter.java:71)
        at com.google.googlejavaformat.java.javadoc.JavadocFormatter.render(JavadocFormatter.java:122)
        at com.google.googlejavaformat.java.javadoc.JavadocFormatter.formatJavadoc(JavadocFormatter.java:52)
        at com.google.googlejavaformat.java.JavaCommentsHelper.rewrite(JavaCommentsHelper.java:47)
        at com.google.googlejavaformat.Doc$Tok.computeBreaks(Doc.java:756)
        at com.google.googlejavaformat.Doc$Level.computeSplit(Doc.java:331)
        at com.google.googlejavaformat.Doc$Level.computeBreakAndSplit(Doc.java:321)
        at com.google.googlejavaformat.Doc$Level.computeBroken(Doc.java:297)
        at com.google.googlejavaformat.Doc$Level.computeBreaks(Doc.java:267)
        at com.google.googlejavaformat.java.Formatter.format(Formatter.java:174)
        at com.google.googlejavaformat.java.Formatter.getFormatReplacements(Formatter.java:291)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:267)
        at com.google.googlejavaformat.java.Formatter.formatSource(Formatter.java:233)
        ... 137 more
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:spotlessJava'.
> java.lang.reflect.InvocationTargetException        
```

What am I missing? `gradle build` is successful without `googleJavaFormat()`.

**Comment by nedtwigg** [comment]
Perhaps related to #1060...

**Comment by AjinxPatil** [comment]
I was able to get past this by specifying an old version of google-java-format.
```
spotless {
  java {
    googleJavaFormat('1.9')
  }
}
```
My dependency graph included guava 29. But the method in
```
Caused by: java.lang.NoSuchMethodError: 'java.lang.Comparable com.google.common.collect.Comparators.max(java.lang.Comparable, java.lang.Comparable)'
```
was introduced in [guava 30](https://guava.dev/releases/30.0-jre/api/docs/com/google/common/collect/Comparators.html#max(T,T)). So I needed to use the latest version of google-java-format that used guava 29 and that is 1.9.

I'm not yet sure how guava and google-java-format are used by spotless. Somehow the guava 29 in my dependency graph is conflicting with spotless with Java 11
https://github.com/diffplug/spotless/blob/c753fae23d60bd99270ff0adb6328d3cd52a13ec/lib/src/main/java/com/diffplug/spotless/java/GoogleJavaFormatStep.java#L96

**Comment by blacelle** [comment]
Reproduced with the simpler:

```
plugins {
    id 'com.diffplug.spotless' version '6.16.0'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'com.google.guava:guava-bom:29.0-jre'
    }
}

dependencies {
    implementation 'com.google.guava:guava:29.0-jre'
}

spotless {
    java {
        googleJavaFormat()
    }
}
```

The issue comes from `id 'io.spring.dependency-management' version '1.0.11.RELEASE'` which enables `dependencyManagement`, and then `mavenBom 'com.google.guava:guava-bom:29.0-jre'` which supposedly forces Guava:29 for all dependencies (including spotless).

Hence I feel this is not a bug, but a feature of `io.spring.dependency-management`
