### ISSUE TITLE
Deadlock while resolving dependencies in Gradle 7.4-rc-1

### ISSUE THREAD

**Issue by davidburstromspotify** [diffplug/spotless#1100]
## Summary

There's an apparent deadlock in Spotless while executing parallel dependency resolution in Gradle 7.4-rc-1.

```
<====---------> 34% EXECUTING [7m 11s]
> :subproject:detekt > Resolve files of :subproject:detekt
> IDLE
> :subproject:spotlessGroovyGradle > Resolve files of :subproject:spotless-1452293708
> :subproject:spotlessKotlinGradle
```

The reason I'm thinking Spotless is involved is because of the stack dump mentioning:

```
"Execution worker for ':' Thread 3" #268 prio=5 os_prio=31 tid=0x00007fac79f61000 nid=0xfd07 waiting for monitor entry [0x0000700016bf2000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.diffplug.gradle.spotless.GradleProvisioner$DedupingProvisioner.provisionWithTransitives(GradleProvisioner.java:71)
        - waiting to lock <0x00000007bdf796b0> (a java.util.HashMap)
        at com.diffplug.spotless.JarState.provisionWithTransitives(JarState.java:68)
```

The full stack dump is attached.
[jstack-dump.txt](https://github.com/diffplug/spotless/files/7887442/jstack-dump.txt)

## Versions

Gradle version: 7.4-rc-1
Java version: 1.8
Spotless version: 6.2.0
KtLint version: 0.43.2

## Configuration

```
        configure<SpotlessExtension> {
            groovyGradle {
                target("*.gradle")
                greclipse().configFile(rootProject.file("config/spotless/greclipse.properties"))
            }

            kotlinGradle {
                target("*.gradle.kts")
                ktlint(ktlintVersion)
            }

            if (plugins.hasPlugin(JavaPlugin::class.java)) {
                java {
                    googleJavaFormat(googleJavaFormatVersion)
                }
            }
        }
```

**Comment by davidburstrom** [comment]
One suspicion is that Gradle 7.4-rc-1 executes two Spotless tasks in the same project in parallel.

**Comment by nedtwigg** [comment]
A workaround might be this is the root `build.gradle`:

```kotlin
configure<SpotlessExtension> {
  predeclareDeps()
}
configure<SpotlessExtensionPredeclare> {
  groovy { greclipse() }
  kotlin { ktlint(ktlintVersion) }
  java { googleJavaFormat(googleJavaFormatVersion) }
}
```

as for root cause:

```
com.diffplug.gradle.spotless.GradleProvisioner$DedupingProvisioner.provisionWithTransitives(GradleProvisioner.java:71)
- waiting to lock <0x00000007bdf796b0> (a java.util.HashMap)
```

It looks to me that L71 gets stuck only if L79 is calling into Gradle code which has deadlocked.

https://github.com/diffplug/spotless/blob/4fdb8dcf23ff9e696fc100642c1c37b547f0d60f/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleProvisioner.java#L67-L85

And looking at the `jstack-dump.txt` for `Thread 4" #269 prio=5 os_prio=31` we can see that is indeed the case

```
at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:51)
	- locked <0x00000007403a5750> (a java.lang.Object)
	at org.gradle.internal.work.DefaultWorkerLeaseService$2.run(DefaultWorkerLeaseService.java:285)
	at org.gradle.internal.work.DefaultWorkerLeaseService$ProjectLockStatisticsImpl.measure(DefaultWorkerLeaseService.java:494)
	at org.gradle.internal.work.DefaultWorkerLeaseService.acquireLocks(DefaultWorkerLeaseService.java:282)
	at org.gradle.internal.work.DefaultWorkerLeaseService.blocking(DefaultWorkerLeaseService.java:226)
	at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForWorkToComplete(DefaultBuildOperationQueue.java:135)
	at org.gradle.internal.operations.DefaultBuildOperationQueue.waitForCompletion(DefaultBuildOperationQueue.java:106)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.executeInParallel(DefaultBuildOperationExecutor.java:143)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.runAll(DefaultBuildOperationExecutor.java:102)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.artifact.ParallelResolveArtifactSet$VisitingSet.visit(ParallelResolveArtifactSet.java:66)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.visitArtifacts(DefaultLenientConfiguration.java:283)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.access$500(DefaultLenientConfiguration.java:73)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$3.run(DefaultLenientConfiguration.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.visitArtifactsWithBuildOperation(DefaultLenientConfiguration.java:239)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.access$200(DefaultLenientConfiguration.java:73)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$2.visitArtifacts(DefaultLenientConfiguration.java:142)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1473)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.visitContents(DefaultConfiguration.java:509)
	at org.gradle.api.internal.file.AbstractFileCollection.getFiles(AbstractFileCollection.java:127)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolve(DefaultConfiguration.java:499)
	at com.diffplug.gradle.spotless.GradleProvisioner.lambda$forConfigurationContainer$1(GradleProvisioner.java:124)
	at com.diffplug.gradle.spotless.GradleProvisioner$$Lambda$1032/1607750177.provisionWithTransitives(Unknown Source)
	at com.diffplug.gradle.spotless.GradleProvisioner$DedupingProvisioner.provisionWithTransitives(GradleProvisioner.java:79)
	- locked <0x00000007bdf796b0> (a java.util.HashMap)
```

The deadlock is here:

https://github.com/gradle/gradle/blob/v7.4.0-RC1/subprojects/base-services/src/main/java/org/gradle/internal/resources/DefaultResourceLockCoordinationService.java#L51

If you search the `jstack-dump.txt` for `0x00000007403a575` there are 7 different threads which have all successfully locked that objects and are in state `WAITING`. Something or other needs to call the `notifyStateChange()` method

https://github.com/gradle/gradle/blob/693625f25f2210d1a3ca866897d69ac221de6811/subprojects/base-services/src/main/java/org/gradle/internal/resources/DefaultResourceLockCoordinationService.java#L92-L97

I'm pretty sure this is a Gradle bug, not Spotless.

**Comment by davidburstrom** [comment]
Thank you very much for your investigation! The problem cannot be reproduced in Gradle 7.4-rc-2, though I also notice that RC 2 doesn't execute tasks in parallel like RC 1 did.
