### ISSUE TITLE
Cannot resolve external dependency com.google.googlejavaformat:google-java-format:1.3

### ISSUE THREAD

**Issue by arulrajnet** [diffplug/spotless#120]
Recently I have upgraded to spotless 3.4.0. Gradle 3.5 and Java 1.8
My spotless config

```
buildscript {
  repositories {
    mavenCentral()
    maven { url 'https://plugins.gradle.org/m2/' }
  }
  dependencies {
    classpath 'com.diffplug.spotless:spotless-plugin-gradle:3.4.0'
    classpath 'com.google.googlejavaformat:google-java-format:1.3'
  }
}

apply plugin: com.diffplug.gradle.spotless.SpotlessPlugin

spotless {
  java {
    googleJavaFormat('1.3')
    custom 'Lambda fix', { it.replace('} )', '})').replace('} ,', '},') }
    importOrder(['java', 'javax', 'org', 'com'])
    trimTrailingWhitespace()
    removeUnusedImports()
  }
  format 'misc', {
    target '**/.gitignore', '**/*.gradle', '**/*.md', '**/*.sh'
    indentWithSpaces(2)
    trimTrailingWhitespace()
    endWithNewline()
  }
}
```
I am getting following error. 

```
:spotlessJava
You probably need to add a repository containing the '[com.google.googlejavaformat:google-java-format:1.3]' artifact, e.g.: 'buildscript { repositories { mavenCentral() }}'
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':detachedConfiguration1'.
        at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFailure(DefaultLenientConfiguration.java:192)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$1.collectFiles(DefaultLenientConfiguration.java:141)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:810)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(DefaultConfiguration.java:376)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getFiles(Unknown Source)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolve(DefaultConfiguration.java:372)
        at com.diffplug.gradle.spotless.GradleProvisioner.lambda$fromProject$16(GradleProvisioner.java:41)
        at com.diffplug.spotless.Provisioner.provisionWithDependencies(Provisioner.java:39)
        at com.diffplug.spotless.JarState.from(JarState.java:62)
        at com.diffplug.spotless.java.GoogleJavaFormatStep$State.<init>(GoogleJavaFormatStep.java:76)
        at com.diffplug.spotless.java.GoogleJavaFormatStep.lambda$create$17(GoogleJavaFormatStep.java:59)
        at com.diffplug.spotless.FormatterStepImpl.calculateState(FormatterStepImpl.java:56)
        at com.diffplug.spotless.LazyForwardingEquality.state(LazyForwardingEquality.java:56)
        at com.diffplug.spotless.LazyForwardingEquality.writeObject(LazyForwardingEquality.java:68)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1028)
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1496)
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1432)
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178)
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.serialize(ValueSnapshotter.java:123)
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.snapshot(ValueSnapshotter.java:115)
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.snapshot(ValueSnapshotter.java:63)
        at org.gradle.api.internal.changedetection.rules.InputPropertiesTaskStateChanges.<init>(InputPropertiesTaskStateChanges.java:52)
        at org.gradle.api.internal.changedetection.rules.TaskUpToDateState.<init>(TaskUpToDateState.java:50)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:170)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:85)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:230)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execute(DefaultGradleLauncher.java:227)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:161)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:95)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Cannot resolve external dependency com.google.googlejavaformat:google-java-format:1.3 because no repositories are defined.
Required by:
    project :
```

If I downgrade to 3.0.0 its just working fine for the same config.

**Comment by nedtwigg** [comment]
At the top of the error message, it says:

```
You probably need to add a repository containing the '[com.google.googlejavaformat:google-java-format:1.3]' artifact, e.g.: 'buildscript { repositories { mavenCentral() }}'
```

If you add `buildscript { repositories { mavenCentral() } }`, it will fix your problem.  This was changed in Spotless `3.3.0`, you can see the reasoning in #99.

**Comment by arulrajnet** [comment]
Please check my spotless config `mavenCentral()` is already there in repositories. I have added `google-java-format` as dependencies too.

**Comment by nedtwigg** [comment]
Does your project have subprojects?  Your project file as written above works for me.  If you have subprojects, you might need a block like this:

```
subprojects {
  buildscript {
    repositories {
      mavenCentral()
    }
  }
}
```

**Comment by arulrajnet** [comment]
@nedtwigg thanks for your commitment. I don't use subproject, its just plain vennila gradle java project. 

To reproduce that clone this repo https://github.com/arulrajnet/gradle-java-template . Then just run `gradle spotlesscheck` . You will get the above mentioned error.

**Comment by nedtwigg** [comment]
The code you linked to does not have `buildscript { repositories { mavenCentral() } }`.  If I add that little snippet to the code, then it works.

**Comment by arulrajnet** [comment]
This [spoless.gradle](https://github.com/arulrajnet/gradle-java-template/blob/master/gradle/spotless.gradle) file already has that snippet. 

But adding that snippet in build.gradle solves the problem. Thanks

**Comment by nedtwigg** [comment]
Ahhhh.  Interesting.  I've never quite understood how `include` works, and now I understand it less than ever ;-)  Glad you got your problem solved, and thanks for sharing the journey here, I'm sure others will bump into this at some point as well :)

**Comment by fvgh** [comment]
The problem is that spotless takes the `buildscript` from [each individual project](https://github.com/diffplug/spotless/blob/81c5461c14ebb55d0904e2235c5d333054788c20/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleProvisioner.java#L39).
But a buildscript closure is bound to the underlying [script](https://docs.gradle.org/3.5/dsl/org.gradle.api.Script.html). 

This is also the reason why you have to configure the repository for all sub-projects. I personally find this not so intuitive. Normally I would expect that the `buildscript` is used, where `apply plugin` for _spotless_ is called. 

When applying the new _spotless_ version to _Junit_, there were [similar problems](https://github.com/junit-team/junit5/pull/860#discussion_r121290121).

@nedtwigg If you agree to my proposal (using `buildscript` where the  `apply plugin` is called), I can have a look whether/how the behavior can be changed.

**Comment by nedtwigg** [comment]
If it's possible, I'm all for it!  Another possible answer is to use the buildscript for the root project.  I think it's reasonable to have different repositories for the build than for the artifacts being built (this was the usecase which drove #99 in the first place), but it's harder to understand needing different buildscript repos for different projects...

**Comment by fvgh** [comment]
`rootProject` is possible, but still does not help (at least according to my understanding of the Gradle Doc) if you use `apply plugin` and have your _spotless_ config in a separate script, which I think is quite common scenario.
Let me look for the right hook and the solution will cover (I'll add tests :smile: ) both scenarios.

**Comment by fvgh** [comment]
@nedtwigg As you assumed, it is not possible to access the buildscript from which the spotless has been created. I looked at the Gradle code and I am pretty sure that I have not missed anything.
What I currently not fully understand are our needs. Do we (except for snapshots and testing) need any other repository than mavenCentral?
I provided a [draft proposal](https://github.com/diffplug/spotless/compare/add_maven_central_if_missing) which always adds mavenCentral to the end of the project build repositories if it is missing. Since gradle uses the first match, this solution should not conflict with any user testing of mavenLocal or proxy configuration.
Wouldn't that solve 99% of the user problems?
I tested it briefly with JUnit and provided a simple unit test.
If you see no conflicts and agree that this should meet most users needs, I would make some more checks and finalize the proposal.

**Comment by nedtwigg** [comment]
This makes me a little nervous.  It's not uncommon for a company to proxy all access to external repositories, so automatically adding mavenCentral is a fairly promiscuous behavior.  One reason for this is to ensure that all artifacts from the public internet have a local proxy, and the second more important reason to proxy is so that every library can be vetted by a security team before it is allowed to be part of the build.

The nice thing about the "root project" workaround I mentioned above is that we would never add a repository that the user hasn't already approved.

**Comment by fvgh** [comment]
As stated before, the solution does not conflict with a proxy. I use Archiva myself, followed the [gradle documentation](https://docs.gradle.org/3.5/userguide/init_scripts.html#sec:configuring_projects_from_an_init_script) for integration.
As long as any repository has been specified by the user in any of its underlying scripts, that one is asked before the `mavenCentral` my solution adds dynamically. 
The gradle proxy documentation and the that [gradle provides repo naming in the API](https://docs.gradle.org/3.5/javadoc/org/gradle/api/artifacts/ArtifactRepositoryContainer.html#DEFAULT_MAVEN_CENTRAL_REPO_NAME) just gave me the idea, that this modification by plugin seems to be a way Gradle wants such problems to be solved and not a hack. I see no other reason why gradle should expose the names of their "internal "defaults.

The drawback with the "root project" is that it does not work for the problem @arulrajnet described.

**Comment by nedtwigg** [comment]
> As long as any repository has been specified by the user in any of its underlying scripts, that one is asked before the mavenCentral my solution adds dynamically.

So let's take the case where the company proxy only contains deps that have been approved by a security team.  Somebody bumps a version number to something which hasn't been approved, but they won't notice because it will get downloaded from mavenCentral(), even though they never once asked that `mavenCentral` be added.

I agree that the `root project` workaround won't fix @arulrajnet's problem, but would it fix your problem with junit?  If so, I think we should improve the error message to include

```
NOTE: the buildscript block must appear in a build.gradle file, this won't work:
include 'myScriptWithBuildScriptBock.gradle'
```

**Comment by fvgh** [comment]
To be hones I consider your example a little bit far fetched:

1. You describe a scenario where the company security is not only worried about the libraries included by the software shipped to the customer, but also about build tools (be are only talking about the buildscript dependencies). I think this is very rare.
2. This company security does not prevent access to Maven Central from developer workstations. I think this will never be the case.

Anyhow, I knew that the proposed solution is controversial. Since in the end you have to answer for the software, you have the final word.

The root project solution you proposed initially is definitely a good enhancement and will also make the description how to configure spotless easier. Code-wise it should be a one-liner, since the tests can remain as they are. Rest is documentation. Do you implement it, or shall I?

**Comment by nedtwigg** [comment]
I agree with you on 2, but I think 1 isn't that rare - e.g. a CI environment that doesn't have access to the public internet.

If you build it, I'd be happy to turn the release crank.

**Comment by fvgh** [comment]
Sorry Ned, I am unsure now what your final word is.
In your previous comment you stated that security concerns should not block for my proposal.
And you mentioned CI.
My experience with CI was actually the key point why I think my proposal is not a hack.
My proxy config looks like this:
```
allprojects {
	buildscript {
	    repositories {
		maven {
			url "http://<ip>:<port>/apache-archiva/repository/internal/"
		}
	    }
	}		
	repositories {
		maven {
			url "http://<ip>:<port>/apache-archiva/repository/internal/"
		}
	}
}
```
This is in my opinion how gradle wants a proxy to be configured. 
If the proxy can can not resolve the extensions and direct access of Maven Central is denied, than you get an error like you do now. I had the problem that my proxy forwards request  to Maven Central. So when #99 was solved, I needed no changes in my build scripts. But when I committed the JUnit changes, JUnit Travis failed. This would not have happen with my proposed solution.
When I said that disallowing access to all Maven Central versions (via proxy or not), I meant 'rare' in the sense that it only affect less than 5% of the users. 95% of the users would be able just to use `spotless` without any further configuration, regardless whether they use multi-project, or configured `spotless` in a dedicated gradle file.
Just let me now what the final solution shall be.

**Comment by nedtwigg** [comment]
Sorry - my final word is that I do not want to add `mavenCentral` automatically to a user's configuration.

If you want to build the rootProject based workaround, then I'll be happy to release it quickly.  But by no means are you obligated to build it :)

**Comment by nedtwigg** [comment]
Can you point us to your buildscriipt?  You might need `allprojects` block rather than `subprojects`.

**Comment by eirnym** [comment]
The same is happening when using `dependencyResolutionManagement`, which is another legal way to provide list of repositories without duplicating the block for each module.
