### ISSUE TITLE
License check breaks if file has no package declaration

### ISSUE THREAD

**Issue by chrisbanes** [diffplug/spotless#135]
I got the following exception:

```
Step 'licenseHeader' found problem in 'src/main/java/me/banes/chris/tivi/extensions/PreferenceExtensions.kt':
Unable to find delimiter regex ^package 
java.lang.IllegalArgumentException: Unable to find delimiter regex ^package 
        at com.diffplug.spotless.generic.LicenseHeaderStep.format(LicenseHeaderStep.java:88)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.Formatter.isClean(Formatter.java:167)
        at com.diffplug.gradle.spotless.SpotlessTask.check(SpotlessTask.java:216)
        at com.diffplug.gradle.spotless.SpotlessTask.performAction(SpotlessTask.java:172)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
```

**Comment by jbduncan** [comment]
That makes a degree of sense to me because, IIUC, Spotless needs a way of identifying what counts as the "top" of a source file so that it can reliably put the specified license header just above.

It occurs to me that we don't provide a `licenseHeader(String, String)` overload for Kotlin files that would allow one to swap out the "top" of a given Kotlin file with a given substring instead of "package"...

**Comment by jbduncan** [comment]
Note: I've just edited my previous comment for clarity.

**Comment by nedtwigg** [comment]
We do provide a way to specify the [start of the file manually](https://github.com/diffplug/spotless/blob/facd2cc3f3bd4d73a5f103d9efd59fa5f30eb677/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L349-L365).  The easiest workaround is to avoid the default package.  If you don't want to change that, then you have to provide the regex yourself, e.g. `licenseHeaderFile('license.txt', 'package|//startfile')` if you want to use the `//startfile` comment to signify the start of the file.  Without a package declaration, it's very difficult to find a regex that will work in the general case.  Files might start with imports, comments, a class declaration, etc.

**Comment by jbduncan** [comment]
> We do provide a way to specify the [start of the file manually](https://github.com/diffplug/spotless/blob/facd2cc3f3bd4d73a5f103d9efd59fa5f30eb677/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java#L349-L365). 

Oops, I missed that. Thanks for correcting me @nedtwigg. :stuck_out_tongue_winking_eye:

**Comment by chrisbanes** [comment]
The default package is used a lot more in Kotlin files, since you can have extensions methods, etc. Thanks though, `licenseHeaderFile('license.txt', '^(package|//startfile)')` works well.

**Comment by nedtwigg** [comment]
Is it required to use the default package in Kotlin, or just more convenient?  If it's required, maybe we should update our docs to include this tip.

**Comment by chrisbanes** [comment]
It's more convenience

**Comment by nedtwigg** [comment]
Roger.  I'll close this for now.  If enough future users bump into this same issue, maybe we'll put the `//startfile` workaround into the docs.
