### ISSUE TITLE
maven-goal 'apply' does not work with ktlint

### ISSUE THREAD

**Issue by bmarwell** [diffplug/spotless#1365]
If you are submitting a **bug**, please include the following:

- [X] summary of problem
- [X] gradle or maven version
- [X] spotless version
- [X] operating system and version
- [X] copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible
- [X] copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

## summary

When running `mvn spotless:apply`, the build will still fail with sth like this:

```
[ERROR] Step 'ktlint' found problem in 'src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/Bug37NewBranchFromMasterIT.kt':
Error on line: 3, column: 1
rule: no-wildcard-imports
Wildcard import
java.lang.AssertionError: Error on line: 3, column: 1
rule: no-wildcard-imports
Wildcard import
```

Instead, it should have formatted the code, not checkingg it.

## Versions

Maven:: any, 3.8.3 and 3.6.3 tested
Spotless: Latest, e.g. 2.27.1
ktlint: 0.47.1

### pluginManagement

```
                <plugin>
                    <groupId>com.diffplug.spotless</groupId>
                    <artifactId>spotless-maven-plugin</artifactId>
                    <version>${spotless.version}</version>
                </plugin>
```

### plugins

Hint: validate/verify phase does not makke a difference here. Even `none` as a phase won't solve the problem

```
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <kotlin>
                        <ktlint>
                            <version>${ktlint.version}</version>
                        </ktlint>
                    </kotlin>
                </configuration>
            </plugin>
```

## full content of any console errors

```bash
$USER@wells ~/git/georgberky/dependency-update-maven-plugin (#11_spotless_ktlint*) $ mvn spotless:apply -e -Dspotless.check.skip=true
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] --< io.github.georgberky.maven.plugins.depsupdate:dependency-update-maven-plugin >--
[INFO] Building io.github.georgberky.maven.plugins.depsupdate:dependency-update-maven-plugin 0.9.0-SNAPSHOT
[INFO] ----------------------------[ maven-plugin ]----------------------------
[INFO] 
[INFO] --- spotless-maven-plugin:2.27.1:apply (default-cli) @ dependency-update-maven-plugin ---
[ERROR] Step 'ktlint' found problem in 'src/test/kotlin/io/github/georgberky/maven/plugins/depsupdate/Bug37NewBranchFromMasterIT.kt':
Error on line: 3, column: 1
rule: no-wildcard-imports
Wildcard import
java.lang.AssertionError: Error on line: 3, column: 1
rule: no-wildcard-imports
Wildcard import
    at com.diffplug.spotless.glue.ktlint.compat.KtLintCompatReporting.report (KtLintCompatReporting.java:23)
    at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot47Dot0Adapter$FormatterCallback.invoke (KtLintCompat0Dot47Dot0Adapter.java:49)
    at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot47Dot0Adapter$FormatterCallback.invoke (KtLintCompat0Dot47Dot0Adapter.java:45)
    at com.pinterest.ktlint.core.KtLint.format (KtLint.kt:300)
    at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot47Dot0Adapter.format (KtLintCompat0Dot47Dot0Adapter.java:78)
    at com.diffplug.spotless.glue.ktlint.KtlintFormatterFunc.applyWithFile (KtlintFormatterFunc.java:71)
    at com.diffplug.spotless.FormatterFunc$NeedsFile.apply (FormatterFunc.java:154)
    at com.diffplug.spotless.FormatterStepImpl$Standard.format (FormatterStepImpl.java:82)
    at com.diffplug.spotless.FormatterStep$Strict.format (FormatterStep.java:88)
    at com.diffplug.spotless.Formatter.compute (Formatter.java:230)
    at com.diffplug.spotless.PaddedCell.calculateDirtyState (PaddedCell.java:203)
    at com.diffplug.spotless.PaddedCell.calculateDirtyState (PaddedCell.java:190)
    at com.diffplug.spotless.maven.SpotlessApplyMojo.process (SpotlessApplyMojo.java:45)
    at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute (AbstractSpotlessMojo.java:198)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:294)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.706 s
[INFO] Finished at: 2022-10-09T14:59:36+02:00
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:$HOME/.sdkman/candidates/maven/current/conf/logging/
constituent[1]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-embedder-3.8.6.jar
constituent[2]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-settings-3.8.6.jar
constituent[3]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-settings-builder-3.8.6.jar
constituent[4]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-plugin-api-3.8.6.jar
constituent[5]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-model-3.8.6.jar
constituent[6]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-model-builder-3.8.6.jar
constituent[7]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-builder-support-3.8.6.jar
constituent[8]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-resolver-api-1.6.3.jar
constituent[9]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-resolver-util-1.6.3.jar
constituent[10]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-shared-utils-3.3.4.jar
constituent[11]: file:$HOME/.sdkman/candidates/maven/current/lib/commons-io-2.6.jar
constituent[12]: file:$HOME/.sdkman/candidates/maven/current/lib/guice-4.2.2-no_aop.jar
constituent[13]: file:$HOME/.sdkman/candidates/maven/current/lib/guava-25.1-android.jar
constituent[14]: file:$HOME/.sdkman/candidates/maven/current/lib/javax.inject-1.jar
constituent[15]: file:$HOME/.sdkman/candidates/maven/current/lib/javax.annotation-api-1.2.jar
constituent[16]: file:$HOME/.sdkman/candidates/maven/current/lib/plexus-utils-3.3.1.jar
constituent[17]: file:$HOME/.sdkman/candidates/maven/current/lib/plexus-sec-dispatcher-2.0.jar
constituent[18]: file:$HOME/.sdkman/candidates/maven/current/lib/plexus-cipher-2.0.jar
constituent[19]: file:$HOME/.sdkman/candidates/maven/current/lib/slf4j-api-1.7.36.jar
constituent[20]: file:$HOME/.sdkman/candidates/maven/current/lib/commons-lang3-3.8.1.jar
constituent[21]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-core-3.8.6.jar
constituent[22]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-repository-metadata-3.8.6.jar
constituent[23]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-artifact-3.8.6.jar
constituent[24]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-resolver-provider-3.8.6.jar
constituent[25]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-resolver-impl-1.6.3.jar
constituent[26]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-resolver-spi-1.6.3.jar
constituent[27]: file:$HOME/.sdkman/candidates/maven/current/lib/org.eclipse.sisu.inject-0.3.5.jar
constituent[28]: file:$HOME/.sdkman/candidates/maven/current/lib/plexus-interpolation-1.26.jar
constituent[29]: file:$HOME/.sdkman/candidates/maven/current/lib/plexus-component-annotations-2.1.0.jar
constituent[30]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-compat-3.8.6.jar
constituent[31]: file:$HOME/.sdkman/candidates/maven/current/lib/wagon-provider-api-3.5.1.jar
constituent[32]: file:$HOME/.sdkman/candidates/maven/current/lib/org.eclipse.sisu.plexus-0.3.5.jar
constituent[33]: file:$HOME/.sdkman/candidates/maven/current/lib/commons-cli-1.4.jar
constituent[34]: file:$HOME/.sdkman/candidates/maven/current/lib/wagon-http-3.5.1-shaded.jar
constituent[35]: file:$HOME/.sdkman/candidates/maven/current/lib/jcl-over-slf4j-1.7.36.jar
constituent[36]: file:$HOME/.sdkman/candidates/maven/current/lib/wagon-file-3.5.1.jar
constituent[37]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-resolver-connector-basic-1.6.3.jar
constituent[38]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-resolver-transport-wagon-1.6.3.jar
constituent[39]: file:$HOME/.sdkman/candidates/maven/current/lib/maven-slf4j-provider-3.8.6.jar
constituent[40]: file:$HOME/.sdkman/candidates/maven/current/lib/jansi-2.4.0.jar
---------------------------------------------------
Exception in thread "main" java.lang.AssertionError: Error on line: 3, column: 1
rule: no-wildcard-imports
Wildcard import
        at com.diffplug.spotless.glue.ktlint.compat.KtLintCompatReporting.report(KtLintCompatReporting.java:23)
        at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot47Dot0Adapter$FormatterCallback.invoke(KtLintCompat0Dot47Dot0Adapter.java:49)
        at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot47Dot0Adapter$FormatterCallback.invoke(KtLintCompat0Dot47Dot0Adapter.java:45)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:300)
        at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot47Dot0Adapter.format(KtLintCompat0Dot47Dot0Adapter.java:78)
        at com.diffplug.spotless.glue.ktlint.KtlintFormatterFunc.applyWithFile(KtlintFormatterFunc.java:71)
        at com.diffplug.spotless.FormatterFunc$NeedsFile.apply(FormatterFunc.java:154)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:82)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:190)
        at com.diffplug.spotless.maven.SpotlessApplyMojo.process(SpotlessApplyMojo.java:45)
        at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute(AbstractSpotlessMojo.java:198)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**Comment by helpermethod** [comment]
This is not really a bug, ktlint just can't handle wildcard imports 🙁. Remove the imports, and it should work.

**Comment by bmarwell** [comment]
Oh, well… thanks :) I was not realising that this might be an issue.
