### ISSUE TITLE
Spotless runs npm command too early

### ISSUE THREAD

**Issue by lkoe** [diffplug/spotless#1540]
We experimented with setting up Spotless (eslint, prettier) for our frontend projects using Node/NPM.

The node installation for the project is managed via the https://github.com/node-gradle/gradle-node-plugin which has the feature to download/install the node distribution on demand.

Since spotless' tslint/prettier integration currently requires a pre-existing node installation on the build machine I wanted to tie those 2 plugins together by supplying the node executable installed by gradle node plugin to spotless.

Turns out - this is not possible atm, as spotless already runs NPM commands during gradles initialization phase (which is a big no-no).

Exepected behaviour:

Spotless should defer running NPM command to the Gradle execution phase - thus enabling the opportunity to set up task dependencies correctly, e.g. in this case to the node setup task provided by the gradle node plugin.

Gradle 7.6
Spotless Gradle Plugin 6.13.0

Exception I get, when supplying the (future) npm executable path to spotless.

```
Caused by: com.diffplug.spotless.npm.NpmProcess$NpmProcessException: Failed to launch npm command 'npm install --no-audit --no-package-lock --no-fund --prefer-offline'.
        at com.diffplug.spotless.npm.NpmProcess.npm(NpmProcess.java:70)
        at com.diffplug.spotless.npm.NpmProcess.npmAwait(NpmProcess.java:50)
        at com.diffplug.spotless.npm.NpmProcess.install(NpmProcess.java:37)
        at com.diffplug.spotless.npm.NpmFormatterStepStateBase.runNpmInstall(NpmFormatterStepStateBase.java:91)
        at com.diffplug.spotless.npm.NpmFormatterStepStateBase.prepareNodeServer(NpmFormatterStepStateBase.java:85)
        at com.diffplug.spotless.npm.NpmFormatterStepStateBase.<init>(NpmFormatterStepStateBase.java:67)
        at com.diffplug.spotless.npm.TsFmtFormatterStep$State.<init>(TsFmtFormatterStep.java:75)
        at com.diffplug.spotless.npm.TsFmtFormatterStep.lambda$create$0(TsFmtFormatterStep.java:47)
        at com.diffplug.spotless.FormatterStepImpl.calculateState(FormatterStepImpl.java:58)
        at com.diffplug.spotless.LazyForwardingEquality.state(LazyForwardingEquality.java:56)
        at com.diffplug.spotless.LazyForwardingEquality.unlazy(LazyForwardingEquality.java:118)
        at com.diffplug.spotless.LazyForwardingEquality.unlazy(LazyForwardingEquality.java:124)
        at com.diffplug.gradle.spotless.JvmLocalCache$LiveCacheKeyImpl.set(JvmLocalCache.java:60)
        at com.diffplug.gradle.spotless.SpotlessTask.setSteps(SpotlessTask.java:168)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl_Decorated.setSteps(Unknown Source)
        at com.diffplug.gradle.spotless.FormatExtension.setupTask(FormatExtension.java:786)
        at com.diffplug.gradle.spotless.TypescriptExtension.setupTask(TypescriptExtension.java:232)
        at com.diffplug.gradle.spotless.SpotlessExtensionImpl.lambda$createFormatTasks$6(SpotlessExtensionImpl.java:70)
```

**Comment by nedtwigg** [comment]
I think we fixed exactly this issue in `6.14.0`.

https://github.com/diffplug/spotless/blob/main/plugin-gradle/CHANGES.md

**Comment by lkoe** [comment]
Ah, dang, I didn't check - but what a coincidence. I'll give it a spin :-)

**Comment by lkoe** [comment]
Thanks, works great 👍

**Comment by nedtwigg** [comment]
Awesome, @simschla built this just in the nick of time :)
