### ISSUE TITLE
Add support for ktlint 0.49.0

### ISSUE THREAD

**Issue by colinrtwhite** [diffplug/spotless#1696]
Hi, thanks for the great library! I'm opening this issue to request support for [ktlint 0.49.0](https://github.com/pinterest/ktlint/releases/tag/0.49.0), which (unfortunately) introduces a number of breaking API changes.

Currently when you run the spotless Gradle plugin `v6.18.0` with this block:

```
kotlin {
    target("**/*.kt", "**/*.kts")
    ktlint(libs.ktlint.get().version)
}
```

It fails with this exception:

<details>
    <summary>Exception</summary>

    2023-05-08T23:06:20.0167941Z java.lang.reflect.InvocationTargetException
    2023-05-08T23:06:20.0168717Z 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:79)
    2023-05-08T23:06:20.0318220Z 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
    2023-05-08T23:06:20.0318729Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
    2023-05-08T23:06:20.0319210Z 	at com.diffplug.spotless.kotlin.KtLintStep$State.createFormat(KtLintStep.java:132)
    2023-05-08T23:06:20.0319683Z 	at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:80)
    2023-05-08T23:06:20.0320139Z 	at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
    2023-05-08T23:06:20.0320556Z 	at com.diffplug.spotless.Formatter.compute(Formatter.java:246)
    2023-05-08T23:06:20.0321015Z 	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
    2023-05-08T23:06:20.0321487Z 	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:190)
    2023-05-08T23:06:20.0322283Z 	at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:105)
    2023-05-08T23:06:20.0322861Z 	at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:89)
    2023-05-08T23:06:20.0323421Z 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    2023-05-08T23:06:20.0323893Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
    2023-05-08T23:06:20.0324286Z 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
    2023-05-08T23:06:20.0324906Z 	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:45)
    2023-05-08T23:06:20.0325558Z 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
    2023-05-08T23:06:20.0326377Z 	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.execute(IncrementalTaskAction.java:26)
    2023-05-08T23:06:20.0327014Z 	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
    2023-05-08T23:06:20.0327788Z 	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:242)
    2023-05-08T23:06:20.0328336Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
    2023-05-08T23:06:20.0328933Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
    2023-05-08T23:06:20.0329540Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
    2023-05-08T23:06:20.0330127Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
    2023-05-08T23:06:20.0330749Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
    2023-05-08T23:06:20.0331366Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
    2023-05-08T23:06:20.0331978Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
    2023-05-08T23:06:20.0332596Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
    2023-05-08T23:06:20.0333184Z 	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:227)
    2023-05-08T23:06:20.0333764Z 	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:210)
    2023-05-08T23:06:20.0334435Z 	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:193)
    2023-05-08T23:06:20.0335038Z 	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:166)
    2023-05-08T23:06:20.0335557Z 	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
    2023-05-08T23:06:20.0336068Z 	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
    2023-05-08T23:06:20.0336534Z 	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
    2023-05-08T23:06:20.0336970Z 	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
    2023-05-08T23:06:20.0337557Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
    2023-05-08T23:06:20.0338275Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
    2023-05-08T23:06:20.0338920Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
    2023-05-08T23:06:20.0339502Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
    2023-05-08T23:06:20.0340120Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
    2023-05-08T23:06:20.0340863Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
    2023-05-08T23:06:20.0341472Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
    2023-05-08T23:06:20.0342098Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
    2023-05-08T23:06:20.0342648Z 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
    2023-05-08T23:06:20.0343128Z 	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
    2023-05-08T23:06:20.0343694Z 	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:67)
    2023-05-08T23:06:20.0344316Z 	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:37)
    2023-05-08T23:06:20.0345008Z 	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:41)
    2023-05-08T23:06:20.0345583Z 	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:74)
    2023-05-08T23:06:20.0346104Z 	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
    2023-05-08T23:06:20.0346611Z 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:50)
    2023-05-08T23:06:20.0347161Z 	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:28)
    2023-05-08T23:06:20.0347918Z 	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.executeDelegateBroadcastingChanges(CaptureStateAfterExecutionStep.java:100)
    2023-05-08T23:06:20.0348761Z 	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:72)
    2023-05-08T23:06:20.0349453Z 	at org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:50)
    2023-05-08T23:06:20.0350098Z 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:40)
    2023-05-08T23:06:20.0350703Z 	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:29)
    2023-05-08T23:06:20.0351299Z 	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:166)
    2023-05-08T23:06:20.0351860Z 	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:70)
    2023-05-08T23:06:20.0352301Z 	at org.gradle.internal.Either$Right.fold(Either.java:175)
    2023-05-08T23:06:20.0352712Z 	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:59)
    2023-05-08T23:06:20.0353201Z 	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:68)
    2023-05-08T23:06:20.0353699Z 	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:46)
    2023-05-08T23:06:20.0354252Z 	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:36)
    2023-05-08T23:06:20.0354854Z 	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:25)
    2023-05-08T23:06:20.0355416Z 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:36)
    2023-05-08T23:06:20.0355963Z 	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:22)
    2023-05-08T23:06:20.0356527Z 	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:91)
    2023-05-08T23:06:20.0357091Z 	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:55)
    2023-05-08T23:06:20.0357538Z 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
    2023-05-08T23:06:20.0357984Z 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
    2023-05-08T23:06:20.0358516Z 	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:37)
    2023-05-08T23:06:20.0359048Z 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:65)
    2023-05-08T23:06:20.0359699Z 	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:36)
    2023-05-08T23:06:20.0360391Z 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
    2023-05-08T23:06:20.0361196Z 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
    2023-05-08T23:06:20.0361892Z 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:76)
    2023-05-08T23:06:20.0362502Z 	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:37)
    2023-05-08T23:06:20.0363045Z 	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:94)
    2023-05-08T23:06:20.0363619Z 	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:49)
    2023-05-08T23:06:20.0364232Z 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:71)
    2023-05-08T23:06:20.0364957Z 	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:45)
    2023-05-08T23:06:20.0365662Z 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.executeWithNonEmptySources(SkipEmptyWorkStep.java:177)
    2023-05-08T23:06:20.0366279Z 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:81)
    2023-05-08T23:06:20.0366810Z 	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:53)
    2023-05-08T23:06:20.0408806Z 	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:32)
    2023-05-08T23:06:20.0409610Z 	at org.gradle.internal.execution.steps.RemoveUntrackedExecutionStateStep.execute(RemoveUntrackedExecutionStateStep.java:21)
    2023-05-08T23:06:20.0410361Z 	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
    2023-05-08T23:06:20.0411142Z 	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
    2023-05-08T23:06:20.0411863Z 	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
    2023-05-08T23:06:20.0412518Z 	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:75)
    2023-05-08T23:06:20.0413115Z 	at org.gradle.internal.execution.steps.CleanupStaleOutputsStep.execute(CleanupStaleOutputsStep.java:41)
    2023-05-08T23:06:20.0413712Z 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:32)
    2023-05-08T23:06:20.0414262Z 	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:287)
    2023-05-08T23:06:20.0414814Z 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:30)
    2023-05-08T23:06:20.0415382Z 	at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:21)
    2023-05-08T23:06:20.0415934Z 	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:37)
    2023-05-08T23:06:20.0416475Z 	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:27)
    2023-05-08T23:06:20.0416983Z 	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:47)
    2023-05-08T23:06:20.0417461Z 	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:34)
    2023-05-08T23:06:20.0417992Z 	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:64)
    2023-05-08T23:06:20.0418645Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:146)
    2023-05-08T23:06:20.0419353Z 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
    2023-05-08T23:06:20.0420383Z 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
    2023-05-08T23:06:20.0421128Z 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
    2023-05-08T23:06:20.0421857Z 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
    2023-05-08T23:06:20.0422514Z 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
    2023-05-08T23:06:20.0423157Z 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
    2023-05-08T23:06:20.0423797Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
    2023-05-08T23:06:20.0424506Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
    2023-05-08T23:06:20.0425159Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
    2023-05-08T23:06:20.0425819Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
    2023-05-08T23:06:20.0426543Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
    2023-05-08T23:06:20.0427184Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
    2023-05-08T23:06:20.0427769Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
    2023-05-08T23:06:20.0428376Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
    2023-05-08T23:06:20.0428999Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
    2023-05-08T23:06:20.0429611Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
    2023-05-08T23:06:20.0430227Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
    2023-05-08T23:06:20.0430864Z 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
    2023-05-08T23:06:20.0431444Z 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
    2023-05-08T23:06:20.0432046Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:337)
    2023-05-08T23:06:20.0432714Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:324)
    2023-05-08T23:06:20.0433413Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:317)
    2023-05-08T23:06:20.0434131Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:303)
    2023-05-08T23:06:20.0434753Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
    2023-05-08T23:06:20.0435282Z 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
    2023-05-08T23:06:20.0435793Z 	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:116)
    2023-05-08T23:06:20.0436397Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:138)
    2023-05-08T23:06:20.0437046Z 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:123)
    2023-05-08T23:06:20.0437624Z 	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:35)
    2023-05-08T23:06:20.0438169Z 	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
    2023-05-08T23:06:20.0438888Z 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
    2023-05-08T23:06:20.0439593Z 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
    2023-05-08T23:06:20.0440300Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
    2023-05-08T23:06:20.0441000Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
    2023-05-08T23:06:20.0441644Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
    2023-05-08T23:06:20.0442296Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
    2023-05-08T23:06:20.0442904Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
    2023-05-08T23:06:20.0443529Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
    2023-05-08T23:06:20.0444140Z 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
    2023-05-08T23:06:20.0444756Z 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
    2023-05-08T23:06:20.0445421Z 	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
    2023-05-08T23:06:20.0446104Z 	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$10(DefaultBuildLifecycleController.java:202)
    2023-05-08T23:06:20.0446742Z 	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:266)
    2023-05-08T23:06:20.0487932Z 	at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$8(StateTransitionController.java:177)
    2023-05-08T23:06:20.0488599Z 	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
    2023-05-08T23:06:20.0489180Z 	at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:177)
    2023-05-08T23:06:20.0489857Z 	at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:202)
    2023-05-08T23:06:20.0490558Z 	at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:209)
    2023-05-08T23:06:20.0491195Z 	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
    2023-05-08T23:06:20.0491811Z 	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
    2023-05-08T23:06:20.0492414Z 	at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:172)
    2023-05-08T23:06:20.0492964Z 	at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:47)
    2023-05-08T23:06:20.0493532Z 	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:191)
    2023-05-08T23:06:20.0494041Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
    2023-05-08T23:06:20.0494465Z 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
    2023-05-08T23:06:20.0494939Z 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    2023-05-08T23:06:20.0495464Z 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
    2023-05-08T23:06:20.0495969Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    2023-05-08T23:06:20.0496456Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    2023-05-08T23:06:20.0497158Z 	at java.base/java.lang.Thread.run(Thread.java:1589)
    2023-05-08T23:06:20.0497597Z Caused by: java.lang.NoClassDefFoundError: com/pinterest/ktlint/core/api/editorconfig/CodeStyleEditorConfigPropertyKt
    2023-05-08T23:06:20.0498234Z 	at com.diffplug.spotless.glue.ktlint.compat.KtLintCompat0Dot48Dot0Adapter.<clinit>(KtLintCompat0Dot48Dot0Adapter.java:58)
    2023-05-08T23:06:20.0498838Z 	at com.diffplug.spotless.glue.ktlint.KtlintFormatterFunc.<init>(KtlintFormatterFunc.java:43)
    2023-05-08T23:06:20.0499435Z 	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
    2023-05-08T23:06:20.0499859Z 	... 161 more
    2023-05-08T23:06:20.0500300Z Caused by: java.lang.ClassNotFoundException: com.pinterest.ktlint.core.api.editorconfig.CodeStyleEditorConfigPropertyKt
    2023-05-08T23:06:20.0500844Z 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
    2023-05-08T23:06:20.0501397Z 	at com.diffplug.spotless.FeatureClassLoader.findClass(FeatureClassLoader.java:79)
    2023-05-08T23:06:20.0501842Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
    2023-05-08T23:06:20.0502221Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
    2023-05-08T23:06:20.0502494Z 	... 164 more
</details>

**Comment by nedtwigg** [comment]
Implemented in `plugin-gradle 6.19.0` and `plugin-maven 2.37.0` thanks to @magneticflux-
