### ISSUE TITLE
Unable to store input properties... when upgrading from 3.6.0 to 3.7.0

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#182]
When updating Spotless from `3.6.0` to `3.7.0`, using gradle version `4.3.1`, I get this error when I try to run `spotlessApply` or `spotlessCheck`.

```
Unable to store input properties for task ':com.diffplug.closet:spotlessJava'. Property 'steps' with value '[com.diffplug.spotless.FilterByFileFormatterStep@18f510bb, com.diffplug.spotless.FormatterStepImpl$Standard@2f74f4c2, com.diffplug.spotless.FormatterStepImpl$Standard@7688f893, com.diffplug.spotless.FormatterStepImpl$Standard@52c51c40, com.diffplug.spotless.FormatterStepImpl$Standard@402d9309]' cannot be serialized.
> java.lang.ClassNotFoundException: com.diffplug.spotless.extra.java.EclipseFormatterStep$State

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.UncheckedIOException: Unable to store input properties for task ':com.diffplug.closet:spotlessJava'. Property 'steps' with value '[com.diffplug.spotless.FilterByFileFormatterStep@18f510bb, com.diffplug.spotless.FormatterStepImpl$Standard@2f74f4c2, com.diffplug.spotless.FormatterStepImpl$Standard@7688f893, com.diffplug.spotless.FormatterStepImpl$Standard@52c51c40, com.diffplug.spotless.FormatterStepImpl$Standard@402d9309]' cannot be serialized.
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.snapshotTaskInputProperties(CacheBackedTaskHistoryRepository.java:316)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.createExecution(CacheBackedTaskHistoryRepository.java:149)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.access$100(CacheBackedTaskHistoryRepository.java:61)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository$1.getCurrentExecution(CacheBackedTaskHistoryRepository.java:114)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.getStates(DefaultTaskArtifactStateRepository.java:201)
        at org.gradle.api.internal.changedetection.changes.DefaultTaskArtifactStateRepository$TaskArtifactStateImpl.isUpToDate(DefaultTaskArtifactStateRepository.java:86)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: org.gradle.api.UncheckedIOException: java.lang.ClassNotFoundException: com.diffplug.spotless.extra.java.EclipseFormatterStep$State
        at org.gradle.api.internal.changedetection.state.SerializedValueSnapshot.populateClass(SerializedValueSnapshot.java:106)
        at org.gradle.api.internal.changedetection.state.SerializedValueSnapshot.hasSameSerializedValue(SerializedValueSnapshot.java:70)
        at org.gradle.api.internal.changedetection.state.SerializedValueSnapshot.snapshot(SerializedValueSnapshot.java:51)
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.snapshot(ValueSnapshotter.java:205)
        at org.gradle.api.internal.changedetection.state.ListValueSnapshot.processList(ListValueSnapshot.java:67)
        at org.gradle.api.internal.changedetection.state.ListValueSnapshot.snapshot(ListValueSnapshot.java:52)
        at org.gradle.api.internal.changedetection.state.ValueSnapshotter.snapshot(ValueSnapshotter.java:205)
        at org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository.snapshotTaskInputProperties(CacheBackedTaskHistoryRepository.java:313)
        ... 32 more
Caused by: java.lang.ClassNotFoundException: com.diffplug.spotless.extra.java.EclipseFormatterStep$State
        at org.gradle.internal.io.ClassLoaderObjectInputStream.resolveClass(ClassLoaderObjectInputStream.java:40)
        at com.diffplug.spotless.LazyForwardingEquality.readObject(LazyForwardingEquality.java:74)
        at org.gradle.api.internal.changedetection.state.SerializedValueSnapshot.populateClass(SerializedValueSnapshot.java:104)
        ... 39 more
```

It's very puzzling, because not much [changed between `3.6.0` and `3.7.0`](https://github.com/diffplug/spotless/compare/gradle/3.6.0...gradle/3.7.0).  The only candidate change I can find at all is [this](https://github.com/diffplug/spotless/commit/9707b1cb2ace1a80c080c0f165fbdbf721255938), but it doesn't make sense that this would cause the problem...  It's a proprietary project, so I can't share source, but for now the only workaround I can find is to stick with `3.6.0`.

**Comment by jbduncan** [comment]
@nedtwigg Would it be practical for you to upgrade your proprietary project to Gradle 4.4.1 and see if it makes a difference?

**Comment by nedtwigg** [comment]
Nope - 4.4.1 brings a different, unrelated problem :)

**Comment by jbduncan** [comment]
Darn, that's a shame. :<

Nothing comes to mind yet, but that might be because it's very late over here in the UK (we just entered the new year quarter of an hour ago!). I'd be interested to see if anyone has any insight on this strange-looking stack trace.

**Comment by jbduncan** [comment]
@nedtwigg Cool, I'm glad you were able to find the solution to this problem! :)
