### ISSUE TITLE
Mangled Enums in 3.8.0

### ISSUE THREAD

**Issue by d1ss0nanz** [diffplug/spotless#189]
[eclipse_formatter_settings.txt](https://github.com/diffplug/spotless/files/1644016/eclipse_formatter_settings.txt)
```
public enum BackupType
{
    FULL("full"), SUPPORT("support");

    private final String _name;

    private static final Map<String, BackupType> BACKUP_TYPE = new ConcurrentHashMap<>();

    BackupType(final String name)
    {
        _name = name;
    }

    @Override
    public String toString()
    {
        return _name;
    }

    static
    {
        for (final BackupType backupType : BackupType.values())
        {
            BACKUP_TYPE.put(backupType.toString(), backupType);
        }
    }

    public static BackupType fromString(final String name)
        throws ResponseException
    {
        ResponseException.assertFalse(name == null || name.isEmpty(), SepMessages.TYPE_MISSING);

        final BackupType backupType = BACKUP_TYPE.get(name);
        ResponseException.assertNotNull(backupType, SepMessages.INVALID_TYPE);

        return backupType;
    }
}

```

Becomes

```
public enum BackupType{FULL("full"),SUPPORT("support");

private final String _name;

private static final Map<String,BackupType>BACKUP_TYPE=new ConcurrentHashMap<>();

BackupType(final String name){_name=name;}

@Override public String toString(){return _name;}

static{for(final BackupType backupType:BackupType.values()){BACKUP_TYPE.put(backupType.toString(),backupType);}}

public static BackupType fromString(final String name)throws ResponseException{ResponseException.assertFalse(name==null||name.isEmpty(),SepMessages.TYPE_MISSING);

final BackupType backupType=BACKUP_TYPE.get(name);ResponseException.assertNotNull(backupType,SepMessages.INVALID_TYPE);

return backupType;}}

```

**Comment by lglossman-ring** [comment]
This might be related to this other issue: https://github.com/diffplug/spotless/issues/77

On my case the error happens if I have annotations at the enum constant level.
Tried with previous versions (3.6.0 and 3.7.0) and the problem was also present there.

I'm using the eclipse formatter with default eclipse rules.

**Comment by nedtwigg** [comment]
What version of eclipse does it work in?  Is Spotless using the [same settings](https://github.com/diffplug/spotless/blob/master/ECLIPSE_SCREENSHOTS.md)?

**Comment by lglossman-ring** [comment]
@nedtwigg Yeah, I tried with all of them and none worked. My local installation of eclipse is the latest stable right now: `Oxygen.2 Release (4.7.2)`.

**Comment by nedtwigg** [comment]
So you're sure that Spotless is pointing to the same config as your running eclipse?

I just uploaded `4.7.2` so you can do `eclipse('4.7.2')`.

**Comment by lglossman-ring** [comment]
@nedtwigg With `eclipse('4.7.2')` it works!

**Comment by nedtwigg** [comment]
Great!  We'll make that the default version starting in Spotless `3.9.0`.

**Comment by d1ss0nanz** [comment]
Sorry, but I have to ask: How is '4.7.2. made available?
When I configure it I get:
Could not find method eclipse() for arguments [4.7.2] on object of type com.diffplug.gradle.spotless.SpotlessExtension.

**Comment by jbduncan** [comment]
@d1ss0nanz I believe that you configure it with `eclipse('4.7.2').configFile(<config-file>)` (from what I personally remember of how Spotless works, which [this part of the docs](https://github.com/diffplug/spotless/tree/master/plugin-gradle#applying-to-java-source) seems to confirm).

The error you're experiencing seems to suggest to me that you're just hitting a syntax error. Would you be able to try again and let us know what happens?

**Comment by d1ss0nanz** [comment]
@jbduncan Thanks, I had forgotten to put it into java {}.

**Comment by d1ss0nanz** [comment]
With eclipse('4.7.2') I get the followin exception:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':spotlessJava'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.diffplug.spotless.ThrowingEx$WrappedAsRuntimeException: java.lang.reflect.InvocationTargetException
        at com.diffplug.spotless.ThrowingEx.asRuntimeRethrowError(ThrowingEx.java:127)
        at com.diffplug.spotless.FormatExceptionPolicyStrict.handleError(FormatExceptionPolicyStrict.java:54)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:241)
        at com.diffplug.spotless.Formatter.isClean(Formatter.java:167)
        at com.diffplug.gradle.spotless.SpotlessTask.check(SpotlessTask.java:263)
        at com.diffplug.gradle.spotless.SpotlessTask.performAction(SpotlessTask.java:205)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 29 more
Caused by: java.lang.reflect.InvocationTargetException
        at com.diffplug.spotless.extra.java.EclipseFormatterStep$State.lambda$createFormat$0(EclipseFormatterStep.java:100)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        ... 43 more
Caused by: java.lang.IllegalStateException: Workspace is closed.
        at org.eclipse.core.resources.ResourcesPlugin.getWorkspace(ResourcesPlugin.java:412)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.createParser(DefaultCodeFormatter.java:332)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.parseSourceCode(DefaultCodeFormatter.java:317)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:213)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:206)
        at org.eclipse.jdt.internal.formatter.CommentsPreparator.formatCode(CommentsPreparator.java:1063)
        at org.eclipse.jdt.internal.formatter.CommentsPreparator.handleFormatCodeTag(CommentsPreparator.java:801)
        at org.eclipse.jdt.internal.formatter.CommentsPreparator.handleHtml(CommentsPreparator.java:665)
        at org.eclipse.jdt.internal.formatter.CommentsPreparator.endVisit(CommentsPreparator.java:621)
        at org.eclipse.jdt.core.dom.TagElement.accept0(TagElement.java:282)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
        at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:2867)
        at org.eclipse.jdt.core.dom.Javadoc.accept0(Javadoc.java:205)
        at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2796)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareComments(DefaultCodeFormatter.java:399)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:222)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:177)
        at org.eclipse.jdt.internal.formatter.DefaultCodeFormatter.format(DefaultCodeFormatter.java:160)
        at com.diffplug.gradle.spotless.java.eclipse.EclipseFormatterStepImpl.format(EclipseFormatterStepImpl.java:38)
        ... 47 more
