### ISSUE TITLE
6.23.2 has breaking ABI changes

### ISSUE THREAD

**Issue by ZacSweers** [diffplug/spotless#1923]
When trying to update to 6.23.2 from 6.22.0, we see the following runtime failure coming from a gradle plugin compiled against 6.22.0. This appears to be the result of a breaking ABI change. Since the library abides by semver, I suspect this is not intentional.

```
Caused by: java.lang.NoSuchMethodError: 'com.diffplug.gradle.spotless.KotlinExtension$KtfmtConfig com.diffplug.gradle.spotless.KotlinExtension.ktfmt(java.lang.String)'	
at slack.gradle.SlackBasePlugin$configureSpotless$1$spotlessFormatters$1$4.execute(SlackBasePlugin.kt:109)	
at slack.gradle.SlackBasePlugin$configureSpotless$1$spotlessFormatters$1$4.execute(SlackBasePlugin.kt:109)	
at com.diffplug.gradle.spotless.SpotlessExtensionPredeclare.lambda$new$0(SpotlessExtensionPredeclare.java:35)	
at com.diffplug.gradle.spotless.SpotlessExtensionPredeclare.lambda$new$1(SpotlessExtensionPredeclare.java:33)	
at org.gradle.internal.code.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:122)	
at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingAction$1.run(DefaultListenerBuildOperationDecorator.java:173)
```

**Comment by Goooler** [comment]
`com.diffplug.gradle.spotless.KotlinExtension$KtfmtConfig` has been moved to `com.diffplug.gradle.spotless.BaseKotlinExtension$KtfmtConfig`.

**Comment by ZacSweers** [comment]
Sure, but that is a breaking ABI change in a semver library. Shouldn't that be a new major release?

**Comment by nedtwigg** [comment]
Thanks for the note @ZacSweers. I have tried to be strict about semver on `spotless-lib`, but for the Gradle plugin I have thought of the consumer as buildscript DSL, so I haven't considered changes such as the above to be a breaking change if they wouldn't break a script.

But makes sense at this point there are probably convention plugins that are using the Gradle plugin. Sorry for the break, from here on out I'll try to enforce this better.

I'm about to publish a 7.0 so that folks who haven't updated Spotless yet won't hit this.

- https://github.com/diffplug/spotless/commit/770a495462923308c43578211ed20acb14a7ea08
