### ISSUE TITLE
Support Gradle Project Isolation

### ISSUE THREAD

**Issue by ZacSweers** [diffplug/spotless#1979]
Gradle 8.5, Spotless Gradle plugin 6.23.3, macOS Sonoma 14.2.1

Project isolation is coming down the pipeline in Gradle and adds new limitations

https://gradle.github.io/configuration-cache/#status_as_of_gradle_8_5

This fails within spotless here

```
org.gradle.api.InvalidUserCodeException: Project ':app' cannot dynamically look up a property in the parent project ':'
	...
	at org.gradle.api.internal.project.DefaultProject.hasProperty(DefaultProject.java:1175)
	at com.diffplug.gradle.spotless.SpotlessExtensionImpl.createFormatTasks(SpotlessExtensionImpl.java:51)
	at com.diffplug.gradle.spotless.SpotlessExtension.maybeCreate(SpotlessExtension.java:262)
	at com.diffplug.gradle.spotless.SpotlessExtension.format(SpotlessExtension.java:246)
	at com.diffplug.gradle.spotless.SpotlessExtension.format(SpotlessExtension.java:224)
```

Specifically, `Project.getProperty`/`Project.hasProperty` look like they need to be replaced with provider APIs instead.

**Comment by ZacSweers** [comment]
Quick note: I'm aware of #987 and #1274, just dropping a separate issue for this specific issue!

**Comment by liutikas** [comment]
Any updates on this work?

**Comment by inorichi** [comment]
I've tried to take a look at this, because this is the only plugin preventing me from enabling isolated projects (which is a huge improvement on this project with ~300 modules).

The changes were:
* Avoiding `findProperty` and `hasProperty` in `GradleCompat`.
* Replacing some `project.getRootProject() == project` with `project.getParent() == null`.
* Replacing some `project.getRootProject()` with `project.getIsolated().getRootProject()`.

But there's one usage left of `.getRootProject()` that is not trivial.

`SpotlessExtension` has a `findRegisterDepsTask` method that creates a `RegisterDependenciesTask` if configuring the root project or references this task of the root project if a subproject, and saves the task in the extension for later use. I think this needs to be refactored to a shared service, but I'm no gradle expert so maybe there's another way I'm not aware of.

**Comment by inorichi** [comment]
The following patch makes `spotlessCheck` and `spotlessApply` work with isolated projects as long as the "predeclared" feature of spotless is not used (which is broken with this patch).

I found that comparing against `getRootProject()` does not make it incompatible with isolated projects, so less changes were needed.

The patch is not good enough to open a PR for it, but I'll leave it here as a starter for the maintainers if they want to take a look.

```diff
diff --git a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/BaseKotlinExtension.java b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/BaseKotlinExtension.java
index 975be992c..f94c4c265 100644
--- a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/BaseKotlinExtension.java
+++ b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/BaseKotlinExtension.java
@@ -160,7 +160,7 @@ public abstract class BaseKotlinExtension extends FormatExtension {
 				Map<String, Object> editorConfigOverride,
 				List<String> customRuleSets) throws IOException {
 			Objects.requireNonNull(version);
-			File defaultEditorConfig = getProject().getRootProject().file(".editorconfig");
+			File defaultEditorConfig = new File(getProject().getRootDir(), ".editorconfig");
 			FileSignature editorConfigPath = defaultEditorConfig.exists() ? FileSignature.signAsList(defaultEditorConfig) : null;
 			this.version = version;
 			this.editorConfigPath = editorConfigPath;
diff --git a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
index 94d965a21..9ce2bbdda 100644
--- a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
+++ b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/FormatExtension.java
@@ -94,11 +94,11 @@ public class FormatExtension {
 	}
 
 	protected final Provisioner provisioner() {
-		return spotless.getRegisterDependenciesTask().getTaskService().get().provisionerFor(spotless);
+		return spotless.getTaskService().get().provisionerFor(spotless);
 	}
 
 	protected final com.diffplug.spotless.extra.P2Provisioner p2Provisioner() {
-		return spotless.getRegisterDependenciesTask().getTaskService().get().p2ProvisionerFor(spotless);
+		return spotless.getTaskService().get().p2ProvisionerFor(spotless);
 	}
 
 	private String formatName() {
@@ -1097,7 +1097,7 @@ public class FormatExtension {
 		LineEnding lineEndings = getLineEndings();
 		task.setLineEndingsPolicy(
 				getProject().provider(() -> lineEndings.createPolicy(projectDir.getAsFile(), () -> totalTarget)));
-		spotless.getRegisterDependenciesTask().hookSubprojectTask(task);
+//		spotless.getRegisterDependenciesTask().hookSubprojectTask(task);
 		task.setupRatchet(getRatchetFrom() != null ? getRatchetFrom() : "");
 	}
 
@@ -1133,7 +1133,7 @@ public class FormatExtension {
 				"Task name must not end with " + SpotlessExtension.APPLY);
 		TaskProvider<SpotlessTaskImpl> spotlessTask = spotless.project.getTasks()
 				.register(taskName + SpotlessTaskService.INDEPENDENT_HELPER, SpotlessTaskImpl.class, task -> {
-					task.init(spotless.getRegisterDependenciesTask().getTaskService());
+					task.init(spotless.getTaskService());
 					setupTask(task);
 					// clean removes the SpotlessCache, so we have to run after clean
 					task.mustRunAfter(BasePlugin.CLEAN_TASK_NAME);
diff --git a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleCompat.java b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleCompat.java
index 16d02b75b..7c5d5a135 100644
--- a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleCompat.java
+++ b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/GradleCompat.java
@@ -27,15 +27,10 @@ public final class GradleCompat {
 		if (value != null) {
 			return value;
 		}
-		@Nullable Object property = project.findProperty(propertyName);
-		if (property != null) {
-			return property.toString();
-		}
 		return null;
 	}
 
 	public static boolean isPropertyPresent(Project project, String propertyName) {
-		return project.getProviders().gradleProperty(propertyName).isPresent() ||
-				project.hasProperty(propertyName);
+		return project.getProviders().gradleProperty(propertyName).isPresent();
 	}
 }
diff --git a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/RegisterDependenciesTask.java b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/RegisterDependenciesTask.java
index 33aded8bd..c6abc7e67 100644
--- a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/RegisterDependenciesTask.java
+++ b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/RegisterDependenciesTask.java
@@ -94,11 +94,6 @@ public abstract class RegisterDependenciesTask extends DefaultTask {
 	// this field is stupid, but we need it, see https://github.com/diffplug/spotless/issues/1260
 	private Provider<SpotlessTaskService> taskService;
 
-	@Internal
-	public Provider<SpotlessTaskService> getTaskService() {
-		return taskService;
-	}
-
 	@Inject
 	protected abstract BuildEventsListenerRegistry getBuildEventsListenerRegistry();
 }
diff --git a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtension.java b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtension.java
index 2ff4896d9..90c71294d 100644
--- a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtension.java
+++ b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtension.java
@@ -27,6 +27,8 @@ import javax.annotation.Nullable;
 import org.gradle.api.Action;
 import org.gradle.api.GradleException;
 import org.gradle.api.Project;
+import org.gradle.api.provider.Provider;
+import org.gradle.api.services.BuildServiceRegistry;
 import org.gradle.api.tasks.TaskContainer;
 import org.gradle.api.tasks.TaskProvider;
 import org.gradle.language.base.plugins.LifecycleBasePlugin;
@@ -35,7 +37,8 @@ import com.diffplug.spotless.LineEnding;
 
 public abstract class SpotlessExtension {
 	final Project project;
-	private final RegisterDependenciesTask registerDependenciesTask;
+	private RegisterDependenciesTask registerDependenciesTask;
+	protected final Provider<SpotlessTaskService> spotlessTaskService;
 
 	protected static final String TASK_GROUP = LifecycleBasePlugin.VERIFICATION_GROUP;
 	protected static final String BUILD_SETUP_TASK_GROUP = "build setup";
@@ -52,13 +55,22 @@ public abstract class SpotlessExtension {
 
 	protected SpotlessExtension(Project project) {
 		this.project = requireNonNull(project);
-		this.registerDependenciesTask = findRegisterDepsTask().get();
+		if (project.getRootProject() == project) {
+			registerDependenciesTask = findRegisterDepsTask().get();
+		}
+
+		BuildServiceRegistry buildServices = project.getGradle().getSharedServices();
+		this.spotlessTaskService = buildServices.registerIfAbsent("SpotlessTaskService", SpotlessTaskService.class, spec -> {});
 	}
 
 	RegisterDependenciesTask getRegisterDependenciesTask() {
 		return registerDependenciesTask;
 	}
 
+	Provider<SpotlessTaskService> getTaskService() {
+		return spotlessTaskService;
+	}
+
 	/** Line endings (if any). */
 	LineEnding lineEndings = LineEnding.GIT_ATTRIBUTES_FAST_ALLSAME;
 
@@ -316,11 +328,11 @@ public abstract class SpotlessExtension {
 	}
 
 	private TaskProvider<RegisterDependenciesTask> findRegisterDepsTask(String taskName) {
-		TaskContainer rootProjectTasks = project.getRootProject().getTasks();
-		if (!rootProjectTasks.getNames().contains(taskName)) {
-			return rootProjectTasks.register(taskName, RegisterDependenciesTask.class, RegisterDependenciesTask::setup);
+		TaskContainer projectTasks = project.getTasks();
+		if (!projectTasks.getNames().contains(taskName)) {
+			return projectTasks.register(taskName, RegisterDependenciesTask.class, RegisterDependenciesTask::setup);
 		} else {
-			return rootProjectTasks.named(taskName, RegisterDependenciesTask.class);
+			return projectTasks.named(taskName, RegisterDependenciesTask.class);
 		}
 	}
 
diff --git a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionImpl.java b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionImpl.java
index 04bfb8d22..b52cfe2be 100644
--- a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionImpl.java
+++ b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionImpl.java
@@ -61,7 +61,7 @@ public class SpotlessExtensionImpl extends SpotlessExtension {
 		// create the SpotlessTask
 		String taskName = EXTENSION + SpotlessPlugin.capitalize(name);
 		TaskProvider<SpotlessTaskImpl> spotlessTask = tasks.register(taskName, SpotlessTaskImpl.class, task -> {
-			task.init(getRegisterDependenciesTask().getTaskService());
+			task.init(spotlessTaskService);
 			task.setGroup(TASK_GROUP);
 			task.getIdeHookState().set(ideHook);
 			// clean removes the SpotlessCache, so we have to run after clean
diff --git a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionPredeclare.java b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionPredeclare.java
index 52a40a22b..5d6428e0a 100644
--- a/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionPredeclare.java
+++ b/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionPredeclare.java
@@ -28,8 +28,8 @@ public class SpotlessExtensionPredeclare extends SpotlessExtension {
 
 	public SpotlessExtensionPredeclare(Project project, GradleProvisioner.Policy policy) {
 		super(project);
-		getRegisterDependenciesTask().getTaskService().get().predeclaredProvisioner = policy.dedupingProvisioner(project);
-		getRegisterDependenciesTask().getTaskService().get().predeclaredP2Provisioner = policy.dedupingP2Provisioner(project);
+		spotlessTaskService.get().predeclaredProvisioner = policy.dedupingProvisioner(project);
+		spotlessTaskService.get().predeclaredP2Provisioner = policy.dedupingP2Provisioner(project);
 		project.afterEvaluate(unused -> toSetup.forEach((name, formatExtension) -> {
 			for (Action<FormatExtension> lazyAction : formatExtension.lazyActions) {
 				lazyAction.execute(formatExtension);
```

**Comment by nedtwigg** [comment]
Thanks for the starter! I will not be working on this. I'm happy to merge PRs that fix it, also happy to merge PRs that make. incremental progress.

**Comment by inorichi** [comment]
I opened #2854 with partial support for isolated projects (it works as long as `predeclareDeps()` is not used in the root project).

**Comment by inorichi** [comment]
Maybe this issue should be closed? Isolated projects will work with most setups after 8.3.0, and I believe predeclared dependencies will always be incompatible with IP because of the way they're designed.
