### ISSUE TITLE
Embed p2 lockfiles for Eclipse JDT

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/spotless#1996]
Starting with `plugin-gradle 6.17.0` and `plugin-maven 2.35.0`, all our eclipse-based formatters migrated to use the [equo p2 client](https://github.com/equodev/equo-ide). This means that they download their dependencies from the p2 repositories where the upstream Eclipse projects publish their jars. The downside is that it doesn't use the normal maven caching & proxies

- #1658
- #1669
- #1687

Relative to other ecosystems, the Eclipse steps have needed a lot more maintenance and had a lot less contributor interest.

We used to solve the p2 -> maven gap by bundling fat jars. Eventually we lost contributor interest to keep that maintained, so we switched to the equo p2 client, which lets us stay up to date with less maintenance burden.

For EclipseJDT, the jars are actually available on maven, we wouldn't have to use the p2 client if we brought back the lockfiles, and with Equo we could make those lockfiles in a more repeatable, easy to maintain way. That would bring at least Eclipse JDT fully back into maven world. If Eclipse CDT or Groovy ever get on board with maven, we could use the same approach there too.

PRs welcome :)

**Comment by BrotherPatrix** [comment]
"The downside is that it doesn't use the normal maven caching & proxies"
This doesn't help with offline builds on restrictive networks. We are not allowed to use internet connection, we had to copy Maven dependencies to a Nexus repository also closed from internet and we managed to get it working after a lot of paperwork, audits and antivirus scans, but because of this plugin, trying to download external dependencies is very difficult because we can't access internet. At least give us the options and documentation to provide these libraries manually, because this doesn't help me at all, at least not me.

**Comment by xjtushilei** [comment]
Our network is not very good, I hope we can improve this problem.  

cc @hydrogen666

**Comment by obfischer** [comment]
We have the same problem as @BrotherPatrix in my current project. So it would be nice to be able to download all required dependencies via Maven.

**Comment by scordio** [comment]
#3000 is my attempt to solve this issue, any feedback is very welcome!

**Comment by einarjohnson** [comment]
has this been resolved? my builds are failing on
```
Caused by: java.io.IOException: Failed to provision P2 dependencies
	at com.diffplug.spotless.extra.P2Provisioner.lambda$createDefault$0(P2Provisioner.java:74)
	at com.diffplug.gradle.spotless.GradleProvisioner$DedupingP2Provisioner.provisionP2Dependencies(GradleProvisioner.java:237)
	at com.diffplug.spotless.extra.EquoBasedStepBuilder.lambda$build$1(EquoBasedStepBuilder.java:127)
	at com.diffplug.spotless.JarState$Promised.get(JarState.java:75)
	... 100 more
Caused by: java.lang.UnsupportedOperationException: We could not parse the content at https://download.eclipse.org/eclipse/updates/4.39/p2.index:

<html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>

	at dev.equo.solstice.p2.P2Client$Folder.<init>(P2Client.java:257)
	at dev.equo.solstice.p2.P2Client.addUnits(P2Client.java:101)
	at dev.equo.solstice.p2.P2Session.populateFrom(P2Session.java:34)
	at dev.equo.solstice.p2.P2Model.queryRaw(P2Model.java:107)
	at dev.equo.solstice.p2.P2Model.query(P2Model.java:136)
	at com.diffplug.spotless.extra.P2Provisioner.lambda$createDefault$0(P2Provisioner.java:61)
	... 103 more
Caused by: java.lang.IllegalStateException: No match found
	at java.base/java.util.regex.Matcher.checkMatch(Matcher.java:1850)
	at java.base/java.util.regex.Matcher.group(Matcher.java:685)
	at dev.equo.solstice.p2.P2Client.getGroup1(P2Client.java:239)
	at dev.equo.solstice.p2.P2Client$Folder.<init>(P2Client.java:255)
	... 108 more
```

**Comment by scordio** [comment]
> has this been resolved?

Not yet, my PR is still under review.

I recently experienced the same with 4.39 (the default version) and was able to make it work by pinning the version to 4.40.

**Comment by einarjohnson** [comment]
@scordio , i am using the gradle spotless plugin, latest version `8.9.0`. Should I go to an older version to bypass this issue?

**Comment by scordio** [comment]
The Spotless plugin version should be good, but you could try to [pin the Eclipse version](https://github.com/diffplug/spotless/blob/main/plugin-gradle/README.md#eclipse-jdt) with something like this:

```
spotless {
  java {
    eclipse('4.40')
```
