### ISSUE TITLE
afterEvaluate AbstractMutationGuard$IllegalMutationException

### ISSUE THREAD

**Issue by gaborbernat** [diffplug/spotless#2268]
I am getting
```
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.diffplug.gradle.spotless.SpotlessExtensionImpl.
        at         at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:70)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:51)
        at org.gradle.internal.extensibility.DefaultConvention.instantiate(DefaultConvention.java:229)
        at org.gradle.internal.extensibility.DefaultConvention.create(DefaultConvention.java:150)
        at org.gradle.internal.extensibility.DefaultConvention.create(DefaultConvention.java:145)
        at com.diffplug.gradle.spotless.SpotlessPlugin.apply(SpotlessPlugin.java:53)
```
due to:
```
Caused by: org.gradle.api.internal.AbstractMutationGuard$IllegalMutationException: Project#afterEvaluate(Action) on project ':x:x-core' cannot be executed in the current context.
        at org.gradle.api.internal.AbstractMutationGuard.createIllegalStateException(AbstractMutationGuard.java:39)
        at org.gradle.api.internal.AbstractMutationGuard.assertMutationAllowed(AbstractMutationGuard.java:34)
        at org.gradle.api.internal.project.DefaultProject.assertMutatingMethodAllowed(DefaultProject.java:1477)
        at org.gradle.api.internal.project.DefaultProject.afterEvaluate(DefaultProject.java:1054)
        at com.diffplug.gradle.spotless.SpotlessExtensionImpl.<init>(SpotlessExtensionImpl.java:42)
```

Following some chat in the Gradle Slack chat:

> looks like a bug in the plugin implementation, so I'd raise a bug
`afterEvalute {}` should be avoided wherever possible, and I don't think it's needed here
https://github.com/diffplug/spotless/blob/1108c14f83d8e96bc86f923acebfedb5e4a43917/plugin-gradle/src/main/java/com/diffplug/gradle/spotless/SpotlessExtensionImpl.java#L42
> you could try setting `enforceCheck = false` and setting up the task dependency in a more idiomatic way

**Comment by PaulFridrick** [comment]
I have the same issue with Gradle 9.0.0 with [configuration on demand](https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html) enabled.
When I execute `./gradlew build` globally in my multi-projects repository everything works as expected, but when I execute a subproject build specifically, like `./gradlew :subproject:build` I have the exception. If I disable configuration on demand, the second command works once again.

<details>

<summary>Here is the updated stack with Spotless (7.2.1), as the lines have slightly moved since the first post.</summary>

```text
Caused by: org.gradle.api.reflect.ObjectInstantiationException: Could not create an instance of type com.diffplug.gradle.spotless.SpotlessExtensionImpl.
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:67)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.newInstanceWithDisplayName(DependencyInjectingInstantiator.java:48)
        at org.gradle.internal.extensibility.DefaultExtensionContainer.instantiate(DefaultExtensionContainer.java:174)
        at org.gradle.internal.extensibility.DefaultExtensionContainer.create(DefaultExtensionContainer.java:95)
        at org.gradle.internal.extensibility.DefaultExtensionContainer.create(DefaultExtensionContainer.java:90)
        at com.diffplug.gradle.spotless.SpotlessPlugin.apply(SpotlessPlugin.java:53)
        at com.diffplug.gradle.spotless.SpotlessPlugin.apply(SpotlessPlugin.java:28)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:55)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:50)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:190)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:54)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:285)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:170)
        at org.gradle.internal.code.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:169)
        ... 374 more
Caused by: org.gradle.api.internal.DefaultMutationGuard$IllegalMutationException: Project#afterEvaluate(Action) on project ':subproject' cannot be executed in the current context.
        at org.gradle.api.internal.DefaultMutationGuard.createIllegalStateException(DefaultMutationGuard.java:102)
        at org.gradle.api.internal.DefaultMutationGuard.assertEagerContext(DefaultMutationGuard.java:55)
        at org.gradle.api.internal.project.DefaultProject.assertEagerContext(DefaultProject.java:1567)
        at org.gradle.api.internal.project.DefaultProject.afterEvaluate(DefaultProject.java:1105)
        at com.diffplug.gradle.spotless.SpotlessExtensionImpl.<init>(SpotlessExtensionImpl.java:46)
        at com.diffplug.gradle.spotless.SpotlessExtensionImpl_Decorated.<init>(Unknown Source)
        at org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeConstructorStrategy.newInstance(AsmBackedClassGenerator.java:2089)
        at org.gradle.internal.instantiation.generator.AbstractClassGenerator$GeneratedClassImpl$GeneratedConstructorImpl.newInstance(AbstractClassGenerator.java:537)
        at org.gradle.internal.instantiation.generator.DependencyInjectingInstantiator.doCreate(DependencyInjectingInstantiator.java:62)
        ... 395 more

```

</details>

**Comment by gaborbernat** [comment]
There does not seem to be enough interest in this, so I am closing it. Thanks for taking a look.
