### ISSUE TITLE
Spotless 7.0 beta 3 and beta4 break configuration cache in GoogleJavaFormatStep

### ISSUE THREAD

**Issue by ZacSweers** [diffplug/spotless#2318]
If you are submitting a **bug**, please include the following:

- [x] summary of problem

Spotless 7.0 beta 3 and beta4 break configuration cache in GoogleJavaFormatStep. 

- Gradle 8.11-rc-1 and 8.10.2

- Spotless Gradle 7.0.0.BETA4 and BETA3

- MacOS Sonoma

- Spotless config: https://github.com/slackhq/foundry/blob/18bc3f44d0aabdd71f01aaa43e9a4d2cbdab7bdb/platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryBasePlugin.kt#L101-L178

```
Caused by: org.gradle.api.GradleException: Add a step with [com.google.googlejavaformat:google-java-format:1.24.0] into the `spotlessPredeclare` block in the root project.	
	at com.diffplug.gradle.spotless.GradleProvisioner$DedupingProvisioner.lambda$new$0(GradleProvisioner.java:99)	
	at com.diffplug.spotless.JarState.provisionWithTransitives(JarState.java:109)	
	at com.diffplug.spotless.JarState.from(JarState.java:98)	
	at com.diffplug.spotless.JarState.from(JarState.java:93)	
	at com.diffplug.spotless.java.GoogleJavaFormatStep.lambda$createInternally$1(GoogleJavaFormatStep.java:106)	
	at com.diffplug.spotless.JarState$Promised.get(JarState.java:53)	
	at com.diffplug.spotless.java.GoogleJavaFormatStep.equalityState(GoogleJavaFormatStep.java:152)	
	at com.diffplug.spotless.FormatterStepSerializationRoundtrip.stateSupplier(FormatterStepSerializationRoundtrip.java:57)	
	at com.diffplug.spotless.ThrowingEx.get(ThrowingEx.java:67)	
	at com.diffplug.spotless.FormatterStepSerializationRoundtrip$HackClone.writeObject(FormatterStepSerializationRoundtrip.java:113)	
	
```

If you're just submitting a feature request or question, no need for the above.

**Comment by davidburstrom** [comment]
Is this the same kind of issue as the following stack trace header indicates?

```org.gradle.internal.cc.base.exceptions.ConfigurationCacheError: Configuration cache state could not be cached: field `backingList` of `com.diffplug.spotless.ConfigurationCacheHackList` bean found in field `stepsInternalEquality` of task `:spotlessKotlin` of type `com.diffplug.gradle.spotless.SpotlessTaskImpl`: error writing value of type 'java.util.ArrayList'```

**Comment by marcphilipp** [comment]
I'm also seeing the error from https://github.com/diffplug/spotless/issues/2318#issuecomment-2461826289 since updating to Gradle 8.11: https://ge.junit.org/s/yychlvofhspe4/failure#1

**Comment by bddckr** [comment]
I'm seeing the same with beta 4 and Gradle 8.11.

After commenting out all `googleJavaFormat` usages for a test, I then get the issue for `ktfmt`. Once commenting that out, it's `gson`.

The inner-most cause is what the original post mentions. The second-to-last cause is the config cache issue mentioned above.

**Comment by nedtwigg** [comment]
This might be resolved in `7.0.0`. If it's not, can you tell me what command to run to replicate the error? I cloned the repo but `spotlessApply` is working for me even with `7.0.0.BETA4`.

**Comment by bddckr** [comment]
I no longer reproduce this issue on Spotless Gradle plugin version `7.0.0` and Gradle `8.12`. Thanks a lot for your work!

**Comment by ZacSweers** [comment]
We still see it with 7.0.3
