### ISSUE TITLE
NoClassDefFoundError on mvn spotless:apply

### ISSUE THREAD

**Issue by JamieMagee** [diffplug/spotless#257]
If you are submitting a **bug**, please include the following:

- summary of problem: NoClassDefFoundError on mvn spotless:apply
- maven version:
```sh
$ mvn -version
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /usr/lib/java/java-8-oracle/jdk1.8.0_162/jre
Default locale: en_US, platform encoding: UTF8
OS name: "linux", version: "4.13.0-1018-azure", arch: "amd64", family: "unix"
```
- spotless version: maven/1.13.0
- operating system and version: Ubuntu 14.04 LTS
- copy-paste your full Spotless configuration block(s), and a link to a public git repo that reproduces the problem if possible:

```xml
<plugin>
<groupId>com.diffplug.spotless</groupId>
<artifactId>spotless-maven-plugin</artifactId>
<version>${spotless.version}</version>
<configuration>
    <java>
        <eclipse>
            <file>${session.executionRootDirectory}/eclipseformat.xml</file>
            <version>${spotless.formatter.version}</version>
        </eclipse>
        <removeUnusedImports/>
        <trimTrailingWhitespace/>
        <importOrder>
            <order>
                java,javax,,
            </order>
        </importOrder>
        <lineEndings>UNIX</lineEndings>
    </java>
</configuration>
</plugin>
```
- copy-paste the full content of any console errors emitted by `gradlew spotless[Apply/Check] --stacktrace`

```java
java.lang.NoClassDefFoundError: Lorg/eclipse/aether/RepositorySystem;
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:659)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:366)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:155)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:610)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:566)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:552)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:858)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:783)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:279)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:211)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:979)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1012)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:975)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1025)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:990)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1036)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:986)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.eclipse.aether.RepositorySystem
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 57 more
```

Also some other relevant output from Maven

```sh
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:1.13.0:apply (default-cli) on project parent: Execution default-cli of goal com.diffplug.spotless:spotless-maven-plugin:1.13.0:apply failed: A required class was missing while executing com.diffplug.spotless:spotless-maven-plugin:1.13.0:apply: Lorg/eclipse/aether/RepositorySystem;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.diffplug.spotless:spotless-maven-plugin:1.13.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/workspace/.m2/repository/com/diffplug/spotless/spotless-maven-plugin/1.13.0/spotless-maven-plugin-1.13.0.jar
[ERROR] urls[1] = file:/workspace/.m2/repository/com/diffplug/spotless/spotless-lib/1.13.0/spotless-lib-1.13.0.jar
[ERROR] urls[2] = file:/workspace/.m2/repository/com/diffplug/spotless/spotless-lib-extra/1.13.0/spotless-lib-extra-1.13.0.jar
[ERROR] urls[3] = file:/workspace/.m2/repository/com/diffplug/durian/durian-core/1.2.0/durian-core-1.2.0.jar
[ERROR] urls[4] = file:/workspace/.m2/repository/com/diffplug/durian/durian-collect/1.2.0/durian-collect-1.2.0.jar
[ERROR] urls[5] = file:/workspace/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/4.9.0.201710071750-r/org.eclipse.jgit-4.9.0.201710071750-r.jar
[ERROR] urls[6] = file:/workspace/.m2/repository/com/jcraft/jsch/0.1.54/jsch-0.1.54.jar
[ERROR] urls[7] = file:/workspace/.m2/repository/com/googlecode/javaewah/JavaEWAH/1.1.6/JavaEWAH-1.1.6.jar
[ERROR] urls[8] = file:/workspace/.m2/repository/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
[ERROR] urls[9] = file:/workspace/.m2/repository/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar
[ERROR] urls[10] = file:/workspace/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[ERROR] urls[11] = file:/workspace/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
[ERROR] urls[12] = file:/workspace/.m2/repository/org/slf4j/slf4j-api/1.7.2/slf4j-api-1.7.2.jar
[ERROR] urls[13] = file:/workspace/.m2/repository/com/googlecode/concurrent-trees/concurrent-trees/2.6.1/concurrent-trees-2.6.1.jar
[ERROR] urls[14] = file:/workspace/.m2/repository/org/codehaus/groovy/groovy-xml/2.4.7/groovy-xml-2.4.7.jar
[ERROR] urls[15] = file:/workspace/.m2/repository/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7.jar
[ERROR] urls[16] = file:/workspace/.m2/repository/org/codehaus/plexus/plexus-resources/1.0.1/plexus-resources-1.0.1.jar
[ERROR] urls[17] = file:/workspace/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar
[ERROR] urls[18] = file:/workspace/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.eclipse.aether.RepositorySystem
[Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by nedtwigg** [comment]
In a future version, can we use this to give an error message like "Requires Maven >= 3.1.0, this was X"?

https://github.com/apache/maven/blob/eb6b212b567c287734a2dbbef3c113fe650f1def/maven-core/src/main/java/org/apache/maven/rtinfo/RuntimeInformation.java#L27-L49

**Comment by lutovich** [comment]
Good idea! I'm not sure if there is a standard way to define a minimum Maven version required by the plugin. Need to investigate this more.

**Comment by nedtwigg** [comment]
I did a quick search, the only API I could find (admittedly as a terribly ignorant maven user) was the link above, which is `@since 3.0.2`.  I tried to trace how `mvn --version` works, but I couldn't find my through the various Realms 😔

**Comment by lutovich** [comment]
Looks like there exists a dedicated [prerequisites](https://maven.apache.org/pom.html#Prerequisites) tag to declare the minimum Maven version. Not sure if it generates a warning or breaks the build. `RuntimeInformation` seems like a good fit as well. I'll try to investigate further this week.

**Comment by JamieMagee** [comment]
Thanks for the quick responses! We only use Ubuntu 14.04 LTS on our CI servers, and we'll definitely be upgrading to something more recent (Most likely 18.04 LTS) before support ends for this version in April 2019.

At this point it looks like my 2 options are:
1. Manually install a more recent Maven version
2. Push to upgrade our CI servers sooner rather than later.

Otherwise, I think it would be a great idea to have a note in the Maven plugin README mentioning that version `3.1.0` is the minimum required version. Enforcing this within Maven would definitely be a plus, but I don't think it's a high priority, and I would be happy with a small note in the documentation.
