### ISSUE TITLE
Apply checks to buildSrc?

### ISSUE THREAD

**Issue by aparmet-toast** [diffplug/spotless#484]
I have a project with Kotlin in the buildSrc directory and I'd like to check those files with ktlint. Is that possible? If there's no out-of-the-box solution, how should I go about getting it set up?

Thanks!

**Comment by nedtwigg** [comment]
Here's how I would do it:

```
buildSrc/
   build.gradle
   src/main/kotlin/ ...
build.gradle <-- in this file
src/main/kotlin/ ...
```

```
spotless {
  kotlin {
    target 'buildSrc/src/main/kotlin/**', 'src/main/kotlin/**'
    ktlint()
...
```

**Comment by vlsi** [comment]
I've just duplicated the config to `buildSrc/build.gradle.kts`, and it works just fine: https://github.com/apache/jmeter/blob/7fa6e9233b499c9a0c079c395a855331daccc8d5/buildSrc/build.gradle.kts#L57-L68

**Comment by nedtwigg** [comment]
How do you run the Spotless tasks?  My understanding (perhaps incorrect) was that `./gradlew spotlessApply` would not run the buildSrc spotlessApply.

**Comment by vlsi** [comment]
Well. It is an either bug or a feature, but it looks like Gradle always executes `:buildSrc:build`

```
$ gw help | cat
Using gradle at '/Users/vladimirsitnikov/Documents/code/jmeter/gradlew' to run buildfile '/Users/vladimirsitnikov/Documents/code/jmeter/build.gradle.kts':

> Task :buildSrc:compileKotlin NO-SOURCE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:batchtest:compileKotlin UP-TO-DATE
> Task :buildSrc:batchtest:compileJava NO-SOURCE
> Task :buildSrc:batchtest:pluginDescriptors UP-TO-DATE
> Task :buildSrc:batchtest:processResources UP-TO-DATE
> Task :buildSrc:batchtest:classes UP-TO-DATE
> Task :buildSrc:batchtest:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:batchtest:jar UP-TO-DATE
> Task :buildSrc:batchtest:assemble UP-TO-DATE
> Task :buildSrc:batchtest:spotlessKotlin UP-TO-DATE
> Task :buildSrc:batchtest:spotlessKotlinCheck UP-TO-DATE
> Task :buildSrc:batchtest:spotlessKotlinGradle UP-TO-DATE
> Task :buildSrc:batchtest:spotlessKotlinGradleCheck UP-TO-DATE
> Task :buildSrc:batchtest:spotlessCheck UP-TO-DATE
> Task :buildSrc:batchtest:compileTestKotlin NO-SOURCE
> Task :buildSrc:batchtest:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:batchtest:compileTestJava NO-SOURCE
> Task :buildSrc:batchtest:processTestResources NO-SOURCE
> Task :buildSrc:batchtest:testClasses UP-TO-DATE
> Task :buildSrc:batchtest:test NO-SOURCE
> Task :buildSrc:spotlessKotlin UP-TO-DATE
> Task :buildSrc:spotlessKotlinCheck UP-TO-DATE
> Task :buildSrc:batchtest:validatePlugins UP-TO-DATE
> Task :buildSrc:batchtest:check UP-TO-DATE
> Task :buildSrc:batchtest:build UP-TO-DATE

> Task :buildSrc:spotlessKotlinGradle FAILED
Step 'ktlint' found problem in 'build.gradle.kts':
Error on line: 21, column: 1
Unexpected indentation (1) (it should be 4)
java.lang.AssertionError: Error on line: 21, column: 1
Unexpected indentation (1) (it should be 4)
        at com.diffplug.spotless.kotlin.KtLintStep$State.lambda$createFormat$0(KtLintStep.java:130)
        at com.sun.proxy.$Proxy133.invoke(Unknown Source)
        at com.pinterest.ktlint.core.KtLint.format(KtLint.kt:402)
```

**Comment by vlsi** [comment]
On the other hand, you are right, `spotlessApply` in the root project does not fix `buildSrc` formatting.

**Comment by nedtwigg** [comment]
Is there any way to run `spotlessApply` in the buildSrc?

**Comment by vlsi** [comment]
`cd buildSrc; gw spotlessApply`

I don't edit `buildSrc` often, so it is just enough for me.

**Comment by nedtwigg** [comment]
what is `gw`?  Your way seems better than the way I've been doing, but I've never figured out how to run spotlessApply within the buildSrc directory.

**Comment by vlsi** [comment]
`gw` is https://github.com/dougborg/gdub (+ I like this patch: https://github.com/dougborg/gdub/pull/27 )

The default `gradlew` works as well, however, I like how `gw` is shorter, and it does not require me to put `../../..` before `gradlew`

```
$ cd buildSrc
$ ../gradlew spotlessApply
```

**Comment by aparmet-toast** [comment]
Ah - my issue is I wasn't actually applying the spotless plugin in my root build.gradle, only for submodules. That combined with targeting `**/*.kt` (since I also need to target Android sources, which don't seem to be picked up by default) does the trick.
