### ISSUE TITLE
Ktlint 0.38.0-alpha01 incompatibility

### ISSUE THREAD

**Issue by ZacSweers** [diffplug/spotless#668]
Looks like the API changed again, filing for posterity. 0.38.0-alpha01 is the first release with Kotlin 1.4.0 support

Spotless (gradle) version: 5.1.1

Repro PR (requires changing the version in dependencies.gradle) - https://github.com/uber/crumb/pull/58

Configuration

```kotlin
kotlin {
  target "**/*.kt"
  ktlint("0.38.0-alpha01).userData(["indent_size": "2", "continuation_indent_size": "4"])
  licenseHeaderFile rootProject.file('spotless/copyright.kt')
}
```

```
Step 'ktlint' found problem in 'crumb-compiler/src/main/kotlin/com/uber/crumb/CrumbProcessor.kt':
com.pinterest.ktlint.core.KtLint.format(java.lang.String, java.lang.Iterable, java.util.Map, kotlin.jvm.functions.Function2)
java.lang.NoSuchMethodException: com.pinterest.ktlint.core.KtLint.format(java.lang.String, java.lang.Iterable, java.util.Map, kotlin.jvm.functions.Function2)
        at java.lang.Class.getMethod(Class.java:1786)
        at com.diffplug.spotless.kotlin.KtLintStep$State.createFormat(KtLintStep.java:181)
        at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:76)
        at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
        at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:201)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:71)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:57)
```

**Comment by ZacSweers** [comment]
Actually, I think that this may be a parsing error due to the `-alpha01`? The signature hasn't changed.

Parsing is here https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/kotlin/KtLintStep.java#L105

**Comment by ZacSweers** [comment]
Yeah I think that's the issue, it expects semver without qualifiers https://github.com/diffplug/spotless/blob/main/lib/src/main/java/com/diffplug/spotless/kotlin/KtLintStep.java#L42

**Comment by JakeWharton** [comment]
It will also break as soon as ktlint goes 1.0 since it only checks the minor version. So if you're going in and fixing it, perhaps only match on `^\(d+)\.\(d+)\.` and add a major version check `== 0` to the conditional logic.
