### ISSUE TITLE
IllegalArgumentException if analysing file in root of Windows mountpoint

### ISSUE THREAD

**Issue by davidburstromspotify** [diffplug/spotless#760]
Given these Gradle files, if they are put in the root of a Windows mount point, the `subpath` extraction fails when running the `spotlessGroovyGradle` task.

`settings.gradle`:
```groovy
rootProject.name = 'bug' // required because of a Gradle bug/feature when the project is in the root
```

`build.gradle`:
```groovy
plugins {
    id 'com.diffplug.spotless' version '5.8.2'
}

spotless {
    groovyGradle {
        target('*.gradle')
        greclipse()
    }   
}
```

Relevant failure output:
```
$ gradle :spotlessGroovyGradle -s
> Task :spotlessGroovyGradle FAILED

Caused by: java.lang.IllegalArgumentException: Expected 'S:/build.gradle' to start with 'S://'
        at com.diffplug.spotless.FileSignature.subpath(FileSignature.java:203)
        at com.diffplug.spotless.extra.GitAttributesLineEndings$CachedEndings.endingFor(GitAttributesLineEndings.java:127)
        at com.diffplug.spotless.extra.GitAttributesLineEndings$RelocatablePolicy.getEndingFor(GitAttributesLineEndings.java:95)
        at com.diffplug.spotless.Formatter.computeLineEndings(Formatter.java:211)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
        at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:71)
        at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:57)
```

Gradle version: 6.7.1
Spotless version: 5.8.2.
JDK version: 1.8.0_252
Operating System: Windows 10 in VirtualBox VM

**Comment by nedtwigg** [comment]
Fixed in `plugin-gradle 5.9.0` and `plugin-maven 2.7.0`.
