### ISSUE TITLE
Spotless does not expose hidden dirs for formatting

### ISSUE THREAD

**Issue by s-ayush2903** [diffplug/spotless#831]
Spotless does not seem to work in hidden directories. We're using prettier coupled with spotless, with this prettier specific config:
```kts
    format("xml") {
      target("**/*.xml")
      prettier(mapOf("prettier" to "2.0.5", "@prettier/plugin-xml" to "0.13.0"))
        .config(mapOf("parser" to "xml", "tabWidth" to 4))
    }
``` 
Concerned code section hyperlink: [here](https://github.com/s-ayush2903/android-fhir/blob/as/spotless-for-entire-project/buildSrc/src/main/kotlin/SpotlessConfig.kt#L38-L42)
Okay so let me explain the scenario. The scene is as follows: 
* We're working on an android codebase developing an application, and as per our directory tree, we have a set of hidden dirs and folders, in which lies the `.idea` folder of ours, and we have a bunch of XML files(most of which are ignored in vcs) but we do check in some of those XML files to vcs out of which is the concerned file: `jarRepositories.xml`(path relative to project: `.idea/jarRepositories.xml`). 
* So when I apply spotless(implicitly prettier on XMLs) on the project, it is formatted incorrectly(i.e., disregards the configuration defined in its declaration), the interesting fact is that when I move the same (incorrectly formatted code patch) to a file/dir that is not hidden in the project tree, it(the XML code patch) gets formats it as expected(i.e., follows the configuration defined in its declaration). An example of incorrectly formatted code patch is linked [here](https://github.com/s-ayush2903/android-fhir/blob/as/spotless-for-entire-project/.idea/jarRepositories.xml#L50-L53). 
* Yeah, I know that I can simply copy-paste that correctly formatted section to the concerned file but don't want to do it. I've tried hardcoding the path to that specific file(to force prettier for that specific file)in spotless config(the spotless config of which I wrote above), but astonishingly, that also doesn't seem to work. 

The problem isn't with prettier I believe, as it is the job of spotless to expose files to the formatters and it doesn't seem to do so. Also as an FYI, I've configured spotless on the entire project(i.e., in the root, not on subprojects only; refs: [application](https://github.com/s-ayush2903/android-fhir/blob/as/spotless-for-entire-project/build.gradle.kts#L22) & [config](https://github.com/s-ayush2903/android-fhir/blob/as/spotless-for-entire-project/buildSrc/src/main/kotlin/SpotlessConfig.kt)).

Spotless version: `5.11.0`

**Comment by nedtwigg** [comment]
My advice would be to not use `**/*.blah`. Instead, use `src/**/*.blah`. There are two reasons:

1. The performance is *much* better
2. Spotless cannot format files from another project (e.g. `a/build.gradle` cannot format files which are part of `b/build.gradle`

I'm not exactly sure what's going on in your case, but one possibility is that you are doing `**/*` in a subproject, and are disappointed that it is not formatting a folder which resides in either a directory above, or in a subproject below.

**Comment by s-ayush2903** [comment]
Hi, thanks for looking into the issue.
I'll now put this in a more clear way:
* I have configured spotless in root of my project, so it exposes each and every file to get formatted(and they do get formatted).
* But when it comes to the hidden directory(which also is exposed for formatting, I believe(as formatting is applied to it)), it(prettier) applies _incorrect_ formatting to that specific XML file only, and to the rest of the XML files it follows the rule defined in prettier config(i.e., applies _correct_ formatting to them).
* I believe there are lesser chances of bug in prettier(as it applies correct formatting on all the files other than this specific one), but maybe spotless alters the configuration(rules told to prettier for applying formatting to XMLs) when it comes to hidden directories.
* It is important to note that spotless does expose that hidden directory to prettier to apply formatting to it, but somewhere in middle of the process, it unknowingly changes the rule defined for prettier
* I suspect there is some problem taking place under the hood in spotless-prettier binding(when the matter is about hidden dirs or the dirs whose name start with a dot `.`) 

I just suspect that spotless alters the rule set for formatting only in case of hidden dirs(the ones whose name begins with a dot `.`)

**Comment by s-ayush2903** [comment]
Some QnA I'll put here(which I believe might be unclear due to very high use of context in the trailing comment):

**Q.** How do I know spotless is _really_ configured on entire project?
**A.** Because when I run `./gradlew sA` it applies formatting on each and every file(even the ones in hidden dir)

**Q.** Why do I suspect spotless-prettier binding?
**A.** Because prettier follows the rule(mentioned in the issue description) for all the XMLs for applying formatting and violates formatting rule only in case of that hidden dir.

**Comment by nedtwigg** [comment]
Have you tried copying the file out of `.hidden`, to see if it gets formatted correctly when it lives somewhere else? This lets us isolate whether it is the location or the content of the file.

**Comment by s-ayush2903** [comment]
Yepp, it does get formatted properly when I copy file contents to some other xml file(that isn't hidden)!

**Comment by s-ayush2903** [comment]
I described it more clearly here:
https://github.com/prettier/prettier/issues/10657

**Comment by nedtwigg** [comment]
Interesting. Internally, Spotless' model is to load a file to a String, then pass it through a series of `Function<String, String>`. We explicitly try to insulate the formatters themselves from the file path. There is an escape hatch which allows a formatter to access the path, because sometimes it matters (e.g. `package-info.java` must be parsed differently than a standard `.java` file).

Here is the prettier formatter:

https://github.com/diffplug/spotless/blob/00ba710a23f27a03cf3dc98e8f769477c9d3bb11/lib/src/main/java/com/diffplug/spotless/npm/PrettierFormatterStep.java#L114-L136

You can see that we are passing the file name along (not the path, just the name) so that prettier can choose how to format based on the file extension.

So I'm stumped. Another diagnostic step we could take:

```gradle
spotless { format 'xmlBlah', {
  ...
  custom 'lastStepWipeout', { str -> "clobber to test" }
} }
```

This adds a final formatter which just replaces all the content with "clobber to test". I wonder if the problem is that some other task is overwriting the `.idea` folder behind your back.

**Comment by s-ayush2903** [comment]
* That snippet gave me a bit deeper insight, Okay, so when I ran spotless after adding that custom `lastStepWipeout` patch, irrespective of the location of the XML file(s)(i.e., no matter hidden or not hidden) prettier failed throwing an HTTP 501 response. * I've attached the logs here, you can see here or if consumes so much space of screen(or requires you to scroll multiple times) then you may give it a look [here at pastebin](https://pastebin.ubuntu.com/p/VtnKRtxQ9h/). 
* And the prettier indeed fails to parse those XMLs, when I put their content on [prettier.io/playground](https://prettier.io/playground).
* Point of problem for prettier: `<?xml version="1.0" encoding="utf-8" ?>` (inferred from their playground)
* Sample XML file in our and many other(android)codebase: [here](https://github.com/google/android-fhir/blob/master/reference/src/main/AndroidManifest.xml)
* Please note that the problem encountered here (with custom step "on") is irrespective of file path

Now I wonder, how prettier is able to format those XMLs earlier(i.e., without that custom step) :thinking: 

<Details>
<Summary>Logs</Summary> 

```jsx
> Task :spotlessXml
 Step 'prettier-format' found problem in '.idea/jarRepositories.xml':
 Unexpected response status code at /prettier/format [HTTP 501] -- (Error while formatting: Error:
 Error parsing XML
 at Object.parse
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/@prettier/plugin-xml/src/parser.js:7:11)
 at Object.parse
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:11370:19)
 at coreFormat
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:14784:25)
 at format
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:15019:75)
 at formatWithCursor
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:15035:12)
 at
 absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:51620:12
 at Object.format
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:51640:12)
 at
 absolute-path/build/spotless-node-modules-prettier-format/serve.js:58:37
 at Layer.handle [as handle_request]
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/express/lib/router/layer.js:95:5)
 at next
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/express/lib/router/route.js:137:13))
 com.diffplug.spotless.npm.SimpleRestClient$SimpleRestResponseException: Unexpected response
 status code at /prettier/format [HTTP 501] -- (Error while formatting: Error: Error parsing XML
 at Object.parse
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/@prettier/plugin-xml/src/parser.js:7:11)
 at Object.parse
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:11370:19)
 at coreFormat
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:14784:25)
 at format
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:15019:75)
 at formatWithCursor
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:15035:12)
 at
 absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:51620:12
 at Object.format
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:51640:12)
 at
 absolute-path/build/spotless-node-modules-prettier-format/serve.js:58:37
 at Layer.handle [as handle_request]
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/express/lib/router/layer.js:95:5)
 at next
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/express/lib/router/route.js:137:13))
 at com.diffplug.spotless.npm.SimpleRestClient.postJson(SimpleRestClient.java:71)
 at com.diffplug.spotless.npm.SimpleRestClient.postJson(SimpleRestClient.java:45)
 at com.diffplug.spotless.npm.PrettierRestService.format(PrettierRestService.java:49)
 at
 com.diffplug.spotless.npm.PrettierFormatterStep$PrettierFilePathPassingFormatterFunc.applyWithFile(PrettierFormatterStep.java:119)
 at com.diffplug.spotless.FormatterFunc$NeedsFile.apply(FormatterFunc.java:154)
 at com.diffplug.spotless.FormatterFunc$Closeable$1.apply(FormatterFunc.java:64)
 at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:78)
 at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
 at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
 at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:212)
 at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
 at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:71)
 at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:57)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at
 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
 at
 org.gradle.api.internal.project.taskfactory.IncrementalInputsTaskAction.doExecute(IncrementalInputsTaskAction.java:32)
 at
 org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
 at
 org.gradle.api.internal.project.taskfactory.AbstractIncrementalTaskAction.execute(AbstractIncrementalTaskAction.java:25)
 at
 org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$2.run(ExecuteActionsTaskExecuter.java:494)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
 at
 org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
 at
 org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
 at
 org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:479)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:462)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$400(ExecuteActionsTaskExecuter.java:105)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.executeWithPreviousOutputFiles(ExecuteActionsTaskExecuter.java:273)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:251)
 at org.gradle.internal.execution.steps.ExecuteStep.lambda$executeOperation$0(ExecuteStep.java:65)
 at java.base/java.util.Optional.map(Optional.java:265)
 at org.gradle.internal.execution.steps.ExecuteStep.executeOperation(ExecuteStep.java:65)
 at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:34)
 at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:47)
 at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:44)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
 at
 org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
 at
 org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
 at
 org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
 at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
 at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:34)
 at
 org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:72)
 at
 org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:42)
 at
 org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:53)
 at
 org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:39)
 at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:44)
 at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:77)
 at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:58)
 at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:54)
 at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:32)
 at
 org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:57)
 at
 org.gradle.internal.execution.steps.CaptureStateAfterExecutionStep.execute(CaptureStateAfterExecutionStep.java:38)
 at
 org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:63)
 at
 org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:30)
 at
 org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:176)
 at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:76)
 at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:47)
 at
 org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:43)
 at
 org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:32)
 at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:39)
 at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:25)
 at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:102)
 at
 org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:95)
 at java.base/java.util.Optional.map(Optional.java:265)
 at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:55)
 at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:39)
 at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:83)
 at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:44)
 at
 org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
 at
 org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
 at
 org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:96)
 at
 org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:52)
 at
 org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:83)
 at
 org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:54)
 at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
 at
 org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:88)
 at java.base/java.util.Optional.orElseGet(Optional.java:369)
 at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:88)
 at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
 at
 org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
 at
 org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:46)
 at
 org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:34)
 at
 org.gradle.internal.execution.steps.AssignWorkspaceStep.lambda$execute$0(AssignWorkspaceStep.java:43)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution$3.withWorkspace(ExecuteActionsTaskExecuter.java:286)
 at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:43)
 at org.gradle.internal.execution.steps.AssignWorkspaceStep.execute(AssignWorkspaceStep.java:33)
 at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:40)
 at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:30)
 at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:54)
 at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:40)
 at
 org.gradle.internal.execution.impl.DefaultExecutionEngine.execute(DefaultExecutionEngine.java:41)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:183)
 at java.base/java.util.Optional.orElseGet(Optional.java:369)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:183)
 at
 org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:173)
 at
 org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:109)
 at
 org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
 at
 org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
 at
 org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
 at
 org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
 at
 org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
 at
 org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
 at
 org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
 at
 org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
 at
 org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
 at
 org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
 at
 org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
 at
 org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
 at
 org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
 at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
 at
 org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:411)
 at
 org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:398)
 at
 org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:391)
 at
 org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:377)
 at
 org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
 at
 org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
 at
 org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
 at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
 at
 org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
 at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
 at
 org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
 at java.base/java.lang.Thread.run(Thread.java:834)

 > Task :spotlessXml FAILED

 Execution failed for task ':spotlessXml'.
 > Unexpected response status code at /prettier/format [HTTP 501] -- (Error while formatting:
 Error: Error parsing XML
 at Object.parse
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/@prettier/plugin-xml/src/parser.js:7:11)
 at Object.parse
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:11370:19)
 at coreFormat
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:14784:25)
 at format
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:15019:75)
 at formatWithCursor
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:15035:12)
 at
 absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:51620:12
 at Object.format
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/prettier/index.js:51640:12)
 at
 absolute-path/build/spotless-node-modules-prettier-format/serve.js:58:37
 at Layer.handle [as handle_request]
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/express/lib/router/layer.js:95:5)
 at next
 (absolute-path/build/spotless-node-modules-prettier-format/node_modules/express/lib/router/route.js:137:13))

 * Try:
 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get
 more log output. Run with --scan to get full insights.
```

**Comment by nedtwigg** [comment]
Did you put the `custom` before or after the `prettier`? And what content does the file end up having?

**Comment by s-ayush2903** [comment]
After(when all indentation maps were declared, in lines after that), and no changes to the file.

**Comment by nedtwigg** [comment]
> no changes to the file.

That means that something besides Spotless must be overwriting the file. Spotless is dumping `clobber to test` into the file, and some other process or gradle task is overwriting it.

**Comment by nedtwigg** [comment]
Sorry we didn't get to the bottom of this, but enough time has passed that I don't think we will. Feel free to reopen if new info is found.
