### ISSUE TITLE
A required class was missing while executing com.diffplug.spotless:spotless-maven-plugin:2.4.2:check: com/sun/source/tree/Tree

### ISSUE THREAD

**Issue by tarunjoshi-lily** [diffplug/spotless#926]
-A required class is missing even though I added the jar `scorcerer-javac` in the dependencies section of the plugin as well.
- Maven version 3.6.0
- spotless version 2.4.2
- Operating system `Description:	Ubuntu 20.04.2 LTS`
- JDK version 11.0.11
-  I am using Flink's github repo https://github.com/apache/flink to run projects under flink-examples and flink-examples-batch project, I created an effective pom.xml for Flink-Examples and also tried to comment out spotless-maven-plugin but i suspect it's being called from Flink force shading plugin.

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.diffplug.spotless:spotless-maven-plugin:2.4.2:check (spotless-check) on project flink-examples-batch_2.11: Execution spotless-check of goal com.diffplug.spotless:spotless-maven-plugin:2.4.2:check failed: A required class was missing while executing com.diffplug.spotless:spotless-maven-plugin:2.4.2:check: com/sun/source/tree/Tree
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.diffplug.spotless:spotless-maven-plugin:2.4.2
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/root/.m2/repository/com/diffplug/spotless/spotless-maven-plugin/2.4.2/spotless-maven-plugin-2.4.2.jar
[ERROR] urls[1] = file:/root/.m2/repository/com/diffplug/spotless/spotless-lib/2.8.0/spotless-lib-2.8.0.jar
[ERROR] urls[2] = file:/root/.m2/repository/com/diffplug/spotless/spotless-lib-extra/2.8.0/spotless-lib-extra-2.8.0.jar
[ERROR] urls[3] = file:/root/.m2/repository/com/googlecode/concurrent-trees/concurrent-trees/2.6.1/concurrent-trees-2.6.1.jar
[ERROR] urls[4] = file:/root/.m2/repository/org/codehaus/groovy/groovy-xml/3.0.3/groovy-xml-3.0.3.jar
[ERROR] urls[5] = file:/root/.m2/repository/org/codehaus/groovy/groovy/3.0.3/groovy-3.0.3.jar
[ERROR] urls[6] = file:/root/.m2/repository/org/codehaus/plexus/plexus-resources/1.0.1/plexus-resources-1.0.1.jar
[ERROR] urls[7] = file:/root/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.8/plexus-utils-3.0.8.jar
[ERROR] urls[8] = file:/root/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
[ERROR] urls[9] = file:/root/.m2/repository/com/diffplug/durian/durian-core/1.2.0/durian-core-1.2.0.jar
[ERROR] urls[10] = file:/root/.m2/repository/com/diffplug/durian/durian-collect/1.2.0/durian-collect-1.2.0.jar
[ERROR] urls[11] = file:/root/.m2/repository/org/eclipse/jgit/org.eclipse.jgit/5.8.0.202006091008-r/org.eclipse.jgit-5.8.0.202006091008-r.jar
[ERROR] urls[12] = file:/root/.m2/repository/com/googlecode/javaewah/JavaEWAH/1.1.7/JavaEWAH-1.1.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>org.apache.flink:flink-examples:1.14-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]

Caused by: java.lang.ClassNotFoundException: com.sun.source.tree.Tree
    at java.net.URLClassLoader.findClass (Unknown Source)
    at com.diffplug.spotless.FeatureClassLoader.findClass (FeatureClassLoader.java:76)
    at java.lang.ClassLoader.loadClass (Unknown Source)
    at java.lang.ClassLoader.loadClass (Unknown Source)
    at java.lang.Class.getDeclaredMethods0 (Native Method)
    at java.lang.Class.privateGetDeclaredMethods (Unknown Source)
    at java.lang.Class.getMethodsRecursive (Unknown Source)
    at java.lang.Class.getMethod0 (Unknown Source)
    at java.lang.Class.getMethod (Unknown Source)
    at com.diffplug.spotless.java.GoogleJavaFormatStep$State.constructRemoveUnusedFunction (GoogleJavaFormatStep.java:189)
    at com.diffplug.spotless.java.GoogleJavaFormatStep$State.createRemoveUnusedImportsOnly (GoogleJavaFormatStep.java:166)
    at com.diffplug.spotless.FormatterStepImpl$Standard.format (FormatterStepImpl.java:76)
    at com.diffplug.spotless.FormatterStep$Strict.format (FormatterStep.java:76)
    at com.diffplug.spotless.Formatter.compute (Formatter.java:230)
    at com.diffplug.spotless.PaddedCell.calculateDirtyState (PaddedCell.java:201)
    at com.diffplug.spotless.PaddedCell.calculateDirtyState (PaddedCell.java:188)
    at com.diffplug.spotless.maven.SpotlessCheckMojo.process (SpotlessCheckMojo.java:52)
    at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute (AbstractSpotlessMojo.java:146)
    at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute (AbstractSpotlessMojo.java:137)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (Unknown Source)
    
Strangely this is not failing on my Macbook

**Comment by ytsophie** [comment]
similar error
Feb 21, 2023 9:12:38 AM com.diffplug.spotless.FormatExceptionPolicyLegacy error
SEVERE: Step 'removeUnusedImports' found problem in 'src/main/java/org/apache/flink/examples/SqlRunner.java':
com/sun/source/tree/Tree
java.lang.NoClassDefFoundError: com/sun/source/tree/Tree
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
	at java.base/java.lang.Class.getMethodsRecursive(Unknown Source)
	at java.base/java.lang.Class.getMethod0(Unknown Source)
	at java.base/java.lang.Class.getMethod(Unknown Source)
	at com.diffplug.spotless.java.GoogleJavaFormatStep$State.constructRemoveUnusedFunction(GoogleJavaFormatStep.java:189)
	at com.diffplug.spotless.java.GoogleJavaFormatStep$State.createRemoveUnusedImportsOnly(GoogleJavaFormatStep.java:166)
	at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:76)
	at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:76)
	at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:201)
	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:188)
	at com.diffplug.spotless.maven.SpotlessCheckMojo.process(SpotlessCheckMojo.java:52)
	at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute(AbstractSpotlessMojo.java:146)
	at com.diffplug.spotless.maven.AbstractSpotlessMojo.execute(AbstractSpotlessMojo.java:137)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: com.sun.source.tree.Tree
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at com.diffplug.spotless.FeatureClassLoader.findClass(FeatureClassLoader.java:76)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 37 more

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] -------------------------

**Comment by Filip-Gen** [comment]
I had the same issue. It was caused when I accidentally switched my Java for the project from JDK to JRE. Using JDK instead of JRE solved the problem.
